'use client';
import { useState } from 'react';

type View='home'|'picks'|'event'|'walk'|'culture'|'experience'|'shop'|'drop'|'map'|'post'|'mypage'|'product'|'cart'|'spot'|'search'|'favorites'|'orders'|'unlock'|'custom'|'eventlist';
type AppState={saved:boolean;booked:boolean;unlocked:boolean;cart:number;post?:string;name:string;color:string};
const picks=[
  {author:'ayako_gifu',title:'柳ケ瀬の路地にある、小さな古書店。',tag:'CULTURE',image:'https://images.unsplash.com/photo-1526243741027-444d633d7365?auto=format&fit=crop&w=800&q=80'},
  {author:'takashi_craft',title:'作家さんのやわらかな器。朝の一杯が少し特別に。',tag:'CRAFT',image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80'},
  {author:'natsuki_foodie',title:'地元の人が通う、午後の喫茶時間。',tag:'FOOD',image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80'}
];
const products=[['志野焼 湯呑み','¥9,900','https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=500&q=80'],['名入れ和傘','¥33,000','https://images.unsplash.com/photo-1558180700-0c1b2684f8cb?auto=format&fit=crop&w=500&q=80'],['美濃和紙 手漉き便箋','¥2,420','https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=500&q=80']];
function Top({title,back,go}:{title:string;back?:boolean;go:(v:View)=>void}){return <header className="topbar"><button className="icon" onClick={()=>back?go('home'):go('picks')} aria-label="戻る">{back?'‹':'⌁'}</button><strong>{title}</strong><button className="icon" onClick={()=>go('post')} aria-label="投稿">＋</button></header>}
function Nav({view,go}:{view:View;go:(v:View)=>void}){const n:[View,string,string][]=[['home','⌂','ホーム'],['picks','⌕','探す'],['map','◫','マップ'],['shop','♡','ショップ'],['mypage','♙','マイページ']];return <nav className="bottomnav">{n.map(([v,i,l])=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}><span>{i}</span>{l}</button>)}</nav>}
function Row({icon,title,sub,to,go}:{icon:string;title:string;sub:string;to:View;go:(v:View)=>void}){return <button className="menu-row" onClick={()=>go(to)}><span className="menu-icon">{icon}</span><div><b>{title}</b><small>{sub}</small></div><i>›</i></button>}
function Home({go}:{go:(v:View)=>void}){return <><Top title="GIFU LOCAL" go={go}/><main className="content home"><section className="hero"><div><span className="eyebrow light">TODAY IN GIFU</span><h1>今日の岐阜、<br/>静かな街角へ。</h1><p>歴史と暮らしが息づく町へ。</p><button className="goldline" onClick={()=>go('walk')}>街を歩く</button></div></section><button className="section-title" onClick={()=>go('picks')}><div><h2>LOCAL PICKS</h2><p>岐阜の人が選ぶ、いま行きたい場所</p></div><span>›</span></button><div className="pick-grid">{picks.map(p=><img key={p.author} src={p.image} alt="おすすめ"/>)}</div><Row icon="✦" title="EVENT" sub="今週末のおすすめイベント" to="eventlist" go={go}/><Row icon="♧" title="WALK" sub="まち歩きルートを探す" to="walk" go={go}/><Row icon="◒" title="CULTURE" sub="岐阜の文化と歴史を知る" to="culture" go={go}/><Row icon="◉" title="EXPERIENCE" sub="つくり手の技を予約する" to="experience" go={go}/><Row icon="□" title="SHOP" sub="文化から、つくり手の品へ" to="shop" go={go}/><button className="drop-teaser" onClick={()=>go('drop')}><span>🔒</span><div><b>DROP</b><small>現地QRで限定商品を解放</small></div><i>›</i></button></main></>}
function Picks({go,s,set}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void}){const data=s.post?[{author:'あなた',title:s.post,tag:'FOOD',image:picks[2].image},...picks]:picks;return <><Top title="LOCAL PICKS" go={go}/><main className="content"><div className="chipbar"><b>すべて</b><button onClick={()=>go('culture')}>ART</button><button onClick={()=>go('culture')}>CRAFT</button><button onClick={()=>go('spot')}>FOOD</button><button onClick={()=>go('post')}>投稿する</button></div>{data.map((p,i)=><button className="post post-button" key={p.author+i} onClick={()=>go(i===1?'culture':'spot')}><div className="post-meta"><span className="avatar">{p.author[0]}</span><b>{p.author}</b><small>{i?'2時間前':'たった今'}</small></div><h3>{p.title}</h3><img src={p.image} alt="投稿写真"/><div className="post-foot"><span>{p.tag}　柳ケ瀬</span><span onClick={(e)=>{e.stopPropagation();set({saved:!s.saved})}}>{s.saved?'♥ 保存済み':'♡ 保存'}</span></div></button>)}</main></>}
function Event({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){return <><Top title="EVENT" back go={go}/><main className="content"><div className="event-photo"/><span className="eyebrow">THIS WEEKEND</span><h1 className="page-title">柳ケ瀬アートマーケット</h1><p className="lead">まちなかで出会う、つくり手の想い。</p><div className="facts"><span>5/24（金）</span><span>11:00–17:00</span><span>柳ケ瀬商店街</span></div><hr/><h3>イベントについて</h3><p className="bodycopy">手仕事の作品やアートが並ぶマーケット。つくり手との会話やライブペインティングも楽しめます。</p><div className="mini-card"><span>周辺おすすめ</span><b>会場から徒歩5分、喫茶 星時でひと休み。</b></div><button className="primary" onClick={()=>{set({booked:true});notice('参加を保存しました。開催前日にお知らせします。')}}>{s.booked?'参加を保存済み':'参加予定に保存'}</button></main></>}
function Walk({go,notice}:{go:(v:View)=>void;notice:(t:string)=>void}){const stops=['和傘屋 旭村','古着屋 IRO','柳ケ瀬倉庫','珈琲屋 珈琲と','ギャラリー 琳'];return <><Top title="柳ケ瀬 Arts & Crafts" back go={go}/><main className="content walk"><p className="route-intro">徒歩約 2.6 km　｜　所要時間 約2時間</p><button className="route-map" onClick={()=>go('map')} aria-label="マップを開く"><span className="route-line"/>{[1,2,3,4,5].map((n,i)=><b key={n} style={{left:`${19+i*16}%`,top:`${57-(i%3)*18}%`}}>{n}</b>)}</button><ol>{stops.map((x,i)=><li key={x}><button onClick={()=>go(i===0?'culture':'spot')}><span>{i+1}</span><div><b>{x}</b><small>{i?'徒歩 '+(i+2)+'分':'和傘づくりの工房見学'}</small></div><em>{[15,20,25,20,25][i]} ›</em></button></li>)}</ol><button className="primary" onClick={()=>notice('ルートをマイページに保存しました。')}>このルートを歩く</button></main></>}
function Culture({go}:{go:(v:View)=>void}){return <><Top title="CULTURE" back go={go}/><main className="content"><div className="culture-photo"/><span className="eyebrow">CRAFT STORY</span><h1 className="page-title">岐阜和傘、<br/>雨の日を美しくする。</h1><p className="bodycopy">細い竹と和紙が生む、軽やかな美しさ。岐阜の町で長く愛される手仕事をたどります。</p><hr/><h3>STORY / PEOPLE / PLACE</h3><p className="bodycopy">工房で作り手に会い、実際に手に取る。文化を知る体験から、暮らしの品との出会いへ。</p><button className="primary" onClick={()=>go('experience')}>和傘づくりを体験する</button><button className="secondary" onClick={()=>go('shop')}>関連する品を見る</button></main></>}
function Experience({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){return <><Top title="EXPERIENCE" back go={go}/><main className="content"><div className="experience-photo"/><span className="eyebrow">CRAFT EXPERIENCE</span><h1 className="page-title">岐阜和傘づくり体験</h1><p className="lead">受け継がれる美意識を、あなたの手で。</p><div className="facts"><span>◷ 120分</span><span>⌖ 柳ケ瀬</span><span>¥8,800〜</span></div><hr/><h3>体験のストーリー</h3><p className="bodycopy">職人の手仕事に触れながら、世界に一つだけの和傘をつくる特別な時間です。</p><button className="primary" onClick={()=>{set({booked:true});notice('予約を受け付けました（デモ）。')}}>{s.booked?'予約を受け付けました':'体験を予約する'}</button></main></>}
function Shop({go}:{go:(v:View)=>void}){return <><Top title="SHOP" back go={go}/><main className="content"><section className="shop-hero"><h1>岐阜の手仕事を、<br/>あなたの暮らしに。</h1></section>{products.map(([n,p,img],i)=><button className="product-row" key={n} onClick={()=>go('product')}><img src={img} alt={n}/><div><span>{i===1?'CUSTOM ORDER':'GIFU CRAFT'}</span><b>{n}</b><strong>{p}</strong></div><i>›</i></button>)}<button className="secondary" onClick={()=>go('culture')}>つくり手の物語を読む</button></main></>}
function Drop({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){return <><Top title="🔒 DROP" back go={go}/><main className="content drop">{!s.unlocked?<section className="unlock"><span>⌘</span><h1>この場所に来た人だけに解放</h1><p>現地QRを読み取って、限定アイテムを解放します。</p><button className="unlock-btn" onClick={()=>{set({unlocked:true});notice('DROPを解放しました。アクセスは3時間有効です。')}}>QRを読み取る</button></section>:<><section className="drop-head"><span className="eyebrow gold">DROP UNLOCKED</span><h1>この場所で解放された<br/>限定アイテム</h1><p>アクセスは3時間有効です。</p></section>{products.map(([n,p,img],i)=><button className="drop-product" key={n} onClick={()=>go('product')}><img src={img} alt={n}/><div><span>{i===0?'現地限定':'限定制作'}</span><b>{n}</b><strong>{p}</strong><small>残り {7-i*2} 点</small></div></button>)}</>}</main></>}
function Map({go}:{go:(v:View)=>void}){const marks=['♜','☕','♜','♨','◒','♜','♧'];return <><Top title="マップで探す" go={go}/><main className="content map"><div className="chipbar"><b>すべて</b><button onClick={()=>go('culture')}>ART</button><button onClick={()=>go('culture')}>CRAFT</button><button onClick={()=>go('spot')}>FOOD</button></div><div className="map-area">{marks.map((m,i)=><button key={i} style={{left:`${10+(i*29)%76}%`,top:`${12+(i*37)%74}%`}} onClick={()=>go(i===1?'spot':'culture')}>{m}</button>)}</div><button className="map-card" onClick={()=>go('spot')}><div><b>喫茶 星時</b><small>カフェ・喫茶　神室町</small><p>レトロな空間で自家焙煎コーヒーを。</p></div><img src={picks[2].image} alt="喫茶店"/></button></main></>}
function Post({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){const [text,setText]=useState('');const [ai,setAi]=useState(false);return <><Top title="おすすめを投稿する" back go={go}/><main className="content form"><div className="upload">＋<small>写真を追加</small></div><label>場所<input defaultValue="喫茶 星時（岐阜市神室町）"/></label><label>ひとことコメント<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="100文字以内で、好きな理由を書いてください。"/></label><label>カテゴリー<select><option>FOOD（カフェ・喫茶）</option><option>CRAFT</option><option>ART</option></select></label><button className="ai-button" onClick={()=>{setAi(true);if(!text)setText('レトロな空間で味わう自家焙煎コーヒー。時間がゆっくり流れます。')}}>✦ AI おすすめサポート</button>{ai&&<div className="ai-result"><b>タイトル案：午後の静かな一杯</b><span>タグ：喫茶 / レトロ / 自家焙煎</span></div>}<button className="primary" onClick={()=>{set({post:text||'午後の静かな一杯'});notice('投稿を送信しました。公開前に確認されます。');go('picks')}}>投稿を送信する</button></main></>}
function MyPage({go,s}:{go:(v:View)=>void;s:AppState}){return <><Top title="マイページ" go={go}/><main className="content"><section className="visitor"><span>GIFU VISITOR ID</span><h2>岐阜 太郎</h2><p>GL-2024-000123</p><div><b>訪問スポット<br/><strong>12</strong></b><b>購入アイテム<br/><strong>{s.cart}</strong></b></div></section><h3>あなたのアクション</h3><div className="status-list"><p>♡ 保存　{s.saved?'1件':'0件'}</p><p>✦ 予約　{s.booked?'1件':'0件'}</p><p>🔒 DROP　{s.unlocked?'解放済み':'未解放'}</p></div><button className="primary" onClick={()=>go('post')}>おすすめを投稿する</button></main></>}
function EventList({go}:{go:(v:View)=>void}){return <><Top title="EVENT 一覧" back go={go}/><main className="content"><div className="chipbar"><b>すべて</b><button>ART</button><button>FOOD</button><button>NIGHT</button></div>{['柳ケ瀬アートマーケット','長良川夜市','珈琲と本のある時間'].map((x,i)=><button className="list-card" key={x} onClick={()=>go('event')}><img src={picks[i].image} alt="イベント"/><div><b>{x}</b><small>5/{24+i}　柳ケ瀬　11:00–17:00</small><span>{['ART','NIGHT','FOOD'][i]}</span></div><i>›</i></button>)}</main></>}
function Search({go}:{go:(v:View)=>void}){const [query,setQuery]=useState('');return <><Top title="検索" back go={go}/><main className="content form"><label>キーワード<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="場所・イベント・文化を検索"/></label><div className="chipbar"><b>すべて</b><button onClick={()=>go('spot')}>場所</button><button onClick={()=>go('eventlist')}>イベント</button><button onClick={()=>go('culture')}>文化</button></div>{query&&<button className="list-card" onClick={()=>go('spot')}><img src={picks[2].image} alt="検索結果"/><div><b>{query}に近いおすすめ</b><small>喫茶 星時　岐阜市神室町</small></div><i>›</i></button>}</main></>}
function Favorites({go,s}:{go:(v:View)=>void;s:AppState}){return <><Top title="保存したコンテンツ" back go={go}/><main className="content"><h1 className="page-title">お気に入り</h1>{s.saved?<button className="list-card" onClick={()=>go('spot')}><img src={picks[2].image} alt="保存済み"/><div><b>喫茶 星時</b><small>カフェ・喫茶　神室町</small></div><i>›</i></button>:<p className="bodycopy">まだ保存したコンテンツはありません。気になる場所や記事を保存できます。</p>}<button className="primary" onClick={()=>go('picks')}>おすすめを探す</button></main></>}
function Orders({go,s}:{go:(v:View)=>void;s:AppState}){return <><Top title="注文履歴" back go={go}/><main className="content"><h1 className="page-title">注文履歴</h1>{s.cart?<button className="list-card" onClick={()=>go('product')}><img src={products[1][2]} alt="和傘"/><div><b>名入れ和傘</b><small>制作中　お届け予定：6月下旬</small><strong>¥33,000</strong></div><i>›</i></button>:<p className="bodycopy">注文履歴はありません。</p>}<button className="secondary" onClick={()=>go('shop')}>ショップを見る</button></main></>}
function Custom({go}:{go:(v:View)=>void}){return <><Top title="カスタムオーダー" back go={go}/><main className="content"><img className="product-main" src={products[1][2]} alt="和傘"/><h1 className="page-title">名入れ和傘をつくる</h1><p className="bodycopy">色・柄・名入れを選んで、職人が一点ずつ制作します。</p><button className="primary" onClick={()=>go('product')}>カスタムを始める</button></main></>}
function Unlock({go}:{go:(v:View)=>void}){return <><Top title="DROP 解放" back go={go}/><main className="content drop"><section className="unlock"><span>⌘</span><h1>現地限定DROP</h1><p>QRを読み取ると、3時間だけ限定商品を閲覧できます。</p><button className="unlock-btn" onClick={()=>go('drop')}>解放画面へ進む</button></section></main></>}
function DesktopNav({view,go}:{view:View;go:(v:View)=>void}){const links:[View,string][]=[['home','ホーム'],['eventlist','イベント'],['picks','スポット'],['experience','体験'],['culture','文化'],['shop','ショップ']];return <header className="desktop-nav"><button className="desk-brand" onClick={()=>go('home')}>GIFU LOCAL</button><span className="desk-tagline">岐阜の人が選ぶ、いい岐阜を発見。</span><button className="desk-search" onClick={()=>go('search')}>スポット・体験・イベントを検索　⌕</button><nav>{links.map(([v,l])=><button key={v} className={view===v?'selected':''} onClick={()=>go(v)}>{l}</button>)}</nav><div className="desk-tools"><button onClick={()=>go('favorites')}>♡<small>お気に入り</small></button><button onClick={()=>go('eventlist')}>♙<small>投稿する</small></button><button onClick={()=>go('mypage')}>♙<small>マイページ</small></button><button onClick={()=>go('map')}>☰<small>メニュー</small></button></div></header>}
function Product({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){const [custom,setCustom]=useState(false);return <><Top title="商品詳細" back go={go}/><main className="content"><img className="product-main" src={products[1][2]} alt="名入れ和傘"/><span className="eyebrow">CRAFT / CUSTOM ORDER</span><h1 className="page-title">名入れ和傘</h1><p className="lead">あなたの名前を、一本の和傘に。</p><h3>色を選ぶ</h3><div className="color-row">{['#071b40','#a92d1d','#4a5840','#74526e','#eee8dc'].map((c,i)=><button key={c} style={{background:c}} className={s.color===['紺','朱','緑','紫','生成'][i]?'chosen':''} onClick={()=>set({color:['紺','朱','緑','紫','生成'][i]})}/>)}</div><label className="inline-label">名入れ<input value={s.name} onChange={e=>set({name:e.target.value})}/></label><button className="ai-button" onClick={()=>setCustom(!custom)}>✦ AI 完成イメージを{custom?'閉じる':'見る'}</button>{custom&&<div className="preview-card"><img src={products[1][2]} alt="完成イメージ"/><b>{s.name} 様　／　{s.color}の和傘</b><small>完成イメージです。実物と完全一致しません。</small></div>}<button className="primary" onClick={()=>{set({cart:s.cart+1});notice('カートに追加しました。');go('cart')}}>カートに入れる　¥33,000</button></main></>}
function Cart({go,s,notice}:{go:(v:View)=>void;s:AppState;notice:(t:string)=>void}){return <><Top title="カート" back go={go}/><main className="content"><h1 className="page-title">カート</h1>{s.cart?<><div className="cart-row"><img src={products[1][2]} alt="商品"/><div><b>名入れ和傘</b><small>{s.name} 様／{s.color}</small><strong>¥33,000 × {s.cart}</strong></div></div><div className="total"><span>合計（税込）</span><b>¥{(33000*s.cart).toLocaleString()}</b></div><button className="primary" onClick={()=>{notice('ご注文を受け付けました（デモ）。');go('mypage')}}>この内容で注文する</button></>:<><p className="bodycopy">カートは空です。文化や体験から、気に入った品を見つけてください。</p><button className="primary" onClick={()=>go('shop')}>ショップを見る</button></>}</main></>}
function Spot({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){return <><Top title="スポット詳細" back go={go}/><main className="content"><img className="spot-main" src={picks[2].image} alt="喫茶 星時"/><span className="eyebrow">CAFE / KAMUROCHO</span><h1 className="page-title">喫茶 星時</h1><p className="lead">レトロな空間で、自家焙煎コーヒーを。</p><div className="facts"><span>⌖ 神室町</span><span>10:00–18:00</span><span>水曜休</span></div><p className="bodycopy">柳ケ瀬を歩いたあと、ゆっくりと一息つける喫茶店。地元の人がすすめる午後の時間です。</p><button className="primary" onClick={()=>{set({saved:!s.saved});notice(s.saved?'保存を解除しました。':'スポットを保存しました。')}}>{s.saved?'保存を解除する':'♡ 保存する'}</button><button className="secondary" onClick={()=>go('walk')}>この店を含むルートを見る</button></main></>}
const pcCards=[
  ['柳ケ瀬の朝をめぐるモーニング','岐阜市','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80'],
  ['長良川沿いの静かな時間','岐阜市','https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=80'],
  ['金華山のふもと、古かばんの時間','金華山','https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80'],
  ['手仕事の器と閉じる朝','美濃','https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80'],
  ['川原町の風景が好き','川原町','https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=800&q=80']
];
const homeImages={
 street:'https://www.city.gifu.lg.jp/_res/projects/default_project/_page_/001/016/632/kippemippe.jpg',
 mountain:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=82',
 river:'https://images.unsplash.com/photo-1437482078695-73f5ca6c96e2?auto=format&fit=crop&w=900&q=82',
 cafe:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=82',
 craft:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=82',
 festival:'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=82',
 fire:'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=900&q=82',
 forest:'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=82',
 food:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=82',
 paper:'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=900&q=82',
 maker:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=700&q=82',
 woman:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=82',
 spring:'https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=900&q=82',
 autumn:'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=900&q=82',
 winter:'https://images.unsplash.com/photo-1483664852095-d6cc6870702d?auto=format&fit=crop&w=900&q=82'
};
type HomeCard={title:string;sub?:string;image:string;tag?:string;to:View};
function HomeFeatureCard({card,go,tall=false}:{card:HomeCard;go:(v:View)=>void;tall?:boolean}){return <button className={`gl-feature-card ${tall?'tall':''}`} onClick={()=>go(card.to)}><img src={card.image} alt=""/><span className="gl-card-shade"/><div>{card.tag&&<em>{card.tag}</em>}<b>{card.title}</b>{card.sub&&<small>{card.sub}</small>}</div></button>}
function HomeShelf({eyebrow,title,copy,cards,go,variant='standard'}:{eyebrow?:string;title:string;copy:string;cards:HomeCard[];go:(v:View)=>void;variant?:'today'|'events'|'picks'|'walk'|'culture'|'experience'|'people'|'shop'|'seasons'|'standard'}){return <section className={`gl-shelf gl-${variant}`}><header><span>{eyebrow}</span><h2>{title}</h2><p>{copy}</p><button onClick={()=>go(cards[0].to)}>もっと見る　›</button></header><div className="gl-shelf-grid">{cards.map((card,i)=><HomeFeatureCard key={i} card={card} go={go} tall={variant==='today'&&i===0}/>)}</div></section>}
function PcHome({go}:{go:(v:View)=>void}){
 const today:HomeCard[]=[{tag:'自然',title:'新緑がまぶしい、付知峡で深呼吸を',sub:'中津川市',image:homeImages.mountain,to:'spot'},{tag:'人・暮らし',title:'古い町並みに灯るあかり、高山の夜散歩',sub:'高山市',image:homeImages.street,to:'walk'},{tag:'クラフト',title:'受け継がれる技と美濃焼、土と炎のものづくり',sub:'土岐市',image:homeImages.craft,to:'culture'},{tag:'食',title:'初夏の恵みをいただく、郷土の味',sub:'郡上市',image:homeImages.food,to:'spot'}];
 const events:HomeCard[]=[{tag:'5/24 土',title:'郡上おどり体験イベント',sub:'5/24（土）– 5/31（土）',image:homeImages.festival,to:'event'},{tag:'5/25 日',title:'ぎふ長良川の鵜飼',sub:'5/25（日）– 10/15（水）',image:homeImages.fire,to:'event'},{tag:'5/27 火',title:'飛騨高山 春の登山祭',sub:'5/27（火）– 5/28（水）',image:homeImages.mountain,to:'event'},{tag:'5/31 土',title:'美濃和紙 あかりアート展',sub:'5/31（土）– 6/8（日）',image:homeImages.paper,to:'event'}];
 const local:HomeCard[]=[{tag:'市民のおすすめ',title:'馬籠宿の街並と茶屋',sub:'静かな朝に歩く石畳。',image:homeImages.street,to:'spot'},{tag:'市民のおすすめ',title:'銚子ヶ滝の滝',sub:'マイナスイオンに包まれて。',image:homeImages.forest,to:'spot'},{tag:'市民のおすすめ',title:'古民家カフェ やなぎ',sub:'川の音と珈琲の時間。',image:homeImages.cafe,to:'spot'},{tag:'市民のおすすめ',title:'天空の茶畑',sub:'岐阜の上に広がる景色。',image:homeImages.mountain,to:'spot'}];
 const walk:HomeCard[]=[{title:'高山の古い町並みめぐり',sub:'約2時間　約3.0km',image:homeImages.street,to:'walk'},{title:'美濃のうだつと和紙の里へ',sub:'約2.5時間　約3.5km',image:homeImages.river,to:'walk'},{title:'川原町と長良川めぐり',sub:'約2時間　約2.8km',image:homeImages.mountain,to:'walk'},{title:'馬籠宿から妻籠宿へ中山道ハイク',sub:'約4時間　約6.0km',image:homeImages.forest,to:'walk'}];
 const cultures:HomeCard[]=[{title:'ART',sub:'アート',image:homeImages.street,to:'culture'},{title:'CRAFT',sub:'工芸',image:homeImages.craft,to:'culture'},{title:'FILM',sub:'映画・映像',image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=700&q=82',to:'culture'},{title:'FASHION',sub:'ファッション',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=700&q=82',to:'culture'},{title:'FOOD',sub:'食',image:homeImages.food,to:'culture'},{title:'NIGHT',sub:'ナイトライフ',image:homeImages.street,to:'culture'}];
 const experiences:HomeCard[]=[{tag:'工芸体験',title:'美濃焼ろくろ体験',sub:'¥4,400〜',image:homeImages.craft,to:'experience'},{tag:'自然・アウトドア',title:'長良川カヤック体験',sub:'¥6,500〜',image:homeImages.river,to:'experience'},{tag:'文化体験',title:'和紙づくり体験',sub:'¥3,300〜',image:homeImages.paper,to:'experience'},{tag:'ガイドツアー',title:'まちの案内人と歩く古い町並みツアー',sub:'¥2,000〜',image:homeImages.street,to:'experience'}];
 const people:HomeCard[]=[{title:'辻 徹さん',sub:'美濃焼職人',image:homeImages.maker,to:'culture'},{title:'鈴木 伸一さん',sub:'陶芸家',image:'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=700&q=82',to:'culture'},{title:'加藤 藍さん',sub:'染色作家',image:homeImages.woman,to:'culture'},{title:'山田 真由美さん',sub:'古民家店主',image:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=700&q=82',to:'culture'}];
 const shop:HomeCard[]=[{tag:'美濃焼',title:'粉引マグカップ',sub:'¥2,660',image:homeImages.craft,to:'product'},{tag:'岐阜和傘',title:'日傘（麻の葉）',sub:'¥22,000',image:'https://images.unsplash.com/photo-1558180700-0c1b2684f8cb?auto=format&fit=crop&w=700&q=82',to:'product'},{tag:'飛騨の木工',title:'山桜のカッティングボード',sub:'¥4,950',image:'https://images.unsplash.com/photo-1528712306091-ed0763094c98?auto=format&fit=crop&w=700&q=82',to:'product'},{tag:'美濃和紙',title:'和紙の便箋セット',sub:'¥1,320',image:homeImages.paper,to:'product'}];
 const seasons:HomeCard[]=[{title:'春（3–5月）',sub:'桜と花めぐり',image:homeImages.spring,to:'eventlist'},{title:'夏（6–8月）',sub:'清流と夏祭り',image:homeImages.river,to:'eventlist'},{title:'秋（9–11月）',sub:'紅葉と味覚',image:homeImages.autumn,to:'eventlist'},{title:'冬（12–2月）',sub:'雪景色と温泉',image:homeImages.winter,to:'eventlist'}];
 return <main className="pc-page gl-home"><section className="gl-hero" style={{backgroundImage:`linear-gradient(90deg,#071523e8 0%,#07152388 48%,#07152325),url('${homeImages.street}')`}}><div><h1>岐阜の“いいね”に出会う。</h1><p>文化、人、工芸、自然、日常の物語。<br/>岐阜の人が選ぶ「いい岐阜」を、<br/>知る・歩く・体験する・買う。</p><button onClick={()=>go('picks')}>はじめての方へ　›</button></div><aside><span>岐阜、再発見。</span><b>LOCAL<br/>RECOMMENDED</b></aside></section><HomeShelf eyebrow="ローカルトピック" title="今日の岐阜" copy="今この瞬間の岐阜を、四つの物語から。" cards={today} go={go} variant="today"/><HomeShelf title="今週のイベント" copy="祭り、灯り、季節の催し" cards={events} go={go} variant="events"/><HomeShelf eyebrow="岐阜の人が選ぶ" title="LOCAL PICKS" copy="市民のおすすめコメント付きで、“いい岐阜”を見つけよう。" cards={local} go={go} variant="picks"/><HomeShelf eyebrow="人気の街歩きルート" title="WALK" copy="テーマでめぐる、とっておきのまち歩き。" cards={walk} go={go} variant="walk"/><HomeShelf eyebrow="文化をめぐる" title="CULTURE" copy="岐阜の文化に触れる多彩なカテゴリー。" cards={cultures} go={go} variant="culture"/><HomeShelf eyebrow="体験する" title="EXPERIENCE" copy="つくる・学ぶ・自然を楽しむ。" cards={experiences} go={go} variant="experience"/><HomeShelf eyebrow="作り手に出会う" title="PEOPLE" copy="岐阜で活躍する作り手やお店の人をご紹介。" cards={people} go={go} variant="people"/><HomeShelf eyebrow="買う" title="SHOP" copy="岐阜の逸品を、厳選して。" cards={shop} go={go} variant="shop"/><HomeShelf eyebrow="季節の岐阜" title="SEASONS" copy="今だけの風景や体験を楽しもう。" cards={seasons} go={go} variant="seasons"/><section className="gl-first"><header><span>✤</span><div><h2>はじめての方へ</h2><p>岐阜LOCALの楽しみ方</p></div></header>{[['知る','おすすめや特集で岐阜を知る','culture'],['歩く','街歩きルートでまちを巡る','walk'],['体験する','文化や自然を体験する','experience'],['つながる','地元の人とつながる','picks']].map(([t,d,v])=><button key={t} onClick={()=>go(v as View)}><b>{t}</b><small>{d}</small></button>)}</section><section className="gl-info"><div><h3>お知らせ</h3><p>2025.05.20　サイトリニューアルのお知らせ</p><p>2025.05.15　岐阜の夏祭り特集を公開しました</p><p>2025.05.01　新しい体験プログラムを追加しました</p></div><div><h3>メールマガジン</h3><p>岐阜の旬な情報やおすすめをお届けします。</p><label><input placeholder="メールアドレスを入力"/><button onClick={()=>alert('登録しました（デモ）')}>登録する ›</button></label></div><div><h3>公式SNS</h3><p>最新情報をSNSでも発信中！</p><b className="gl-social">◎　●　𝕏　▶　●</b></div></section><footer className="gl-footer"><div><b>✤ GIFU LOCAL</b><p>岐阜の人が選ぶ「いい岐阜」を、<br/>知る・歩く・体験する・買う。</p></div>{[['知る・探す','スポットを探す','イベントを探す'],['歩く','街歩きルート','エリアから探す'],['体験する','体験一覧','体験レポート'],['作り手に出会う','作り手一覧','インタビュー'],['GIFU LOCALについて','はじめての方へ','お問い合わせ']].map(x=><div key={x[0]}><b>{x[0]}</b><small>{x[1]}</small><small>{x[2]}</small></div>)}<p className="gl-copy">© GIFU LOCAL All Rights Reserved.</p></footer></main>
}
function PcCard({item,go,to='spot'}:{item:string[];go:(v:View)=>void;to?:View}){return <button className="pc-card" onClick={()=>go(to)}><img src={item[2]} alt=""/><b>{item[0]}</b><small>⌖ {item[1]}</small><em>♡ 28　◌ 3</em></button>}
function DesktopReference({view,go,s,set,notice}:{view:View;go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){
 const cats:[View,string,string][]=[['picks','LOCAL PICKS','地元のおすすめ'],['eventlist','EVENT','イベント'],['walk','WALK / ROUTE','まち歩き'],['culture','CULTURE','文化を知る'],['experience','EXPERIENCE','体験する'],['shop','SHOP','買いもの']];
 if(view==='home')return <PcHome go={go}/>;
 const titles:Partial<Record<View,[string,string]>>={picks:['LOCAL PICKS','地元の人の “好き” が集まる場所'],eventlist:['EVENT','岐阜のいまを楽しむイベント・催し'],walk:['WALK / ROUTE','まちを歩き、岐阜のもっと文化'],experience:['EXPERIENCE','つくる・学ぶ・触れる'],shop:['SHOP','岐阜の手仕事が並ぶ、日々を豊かにする品']};
 if(titles[view]){const [title,sub]=titles[view]!;const to=view==='shop'?'product':view==='eventlist'?'event':view==='experience'?'experience':view==='walk'?'walk':'spot';return <main className="pc-page pc-list"><header><div><h1>{title}</h1><p>{sub}</p></div><button className="pc-outline" onClick={()=>go(view==='shop'?'shop':view==='walk'?'map':'post')}>{view==='walk'?'ルートを地図で見る':view==='shop'?'ショップを閲覧する':'投稿する'}</button></header><div className="pc-filters"><b>すべて</b><span>グルメ</span><span>カフェ</span><span>文化</span><span>自然・景観</span><span>買いもの</span><span>子どもと</span></div><section className="pc-card-grid">{pcCards.map((x,i)=><PcCard key={i} item={x} go={go} to={to as View}/>)}</section></main>}
 if(view==='culture')return <main className="pc-page pc-culture"><section className="pc-culture-hero"><div><span>＜ 文化一覧に戻る</span><h1>岐阜和傘</h1><b>美しさをひらく、夏のかたち</b><p>細やかな和紙と、手仕事が生む美しさ。岐阜の町の文化を、つくり手の言葉からたどります。</p></div></section><aside><b>主な産地</b><p>岐阜市・美濃市</p><b>関連する体験</b><button onClick={()=>go('experience')}>和傘づくり体験へ</button></aside><section className="pc-maker"><img src={pcCards[3][2]} alt=""/><div><b>つくり手　松田 和傘工房</b><p>和紙と竹の魅力を、今の暮らしへ。</p><button onClick={()=>go('shop')}>詳しく見る</button></div></section></main>;
 if(view==='map')return <main className="pc-page pc-map"><aside><input placeholder="スポット・イベントを検索"/><b>すべて</b><span>● おすすめスポット</span><span>● イベント</span><span>● 体験</span><span>● 文化</span><button onClick={()=>go('picks')}>リストを表示</button></aside><section className="pc-map-canvas">{['♜','☕','✦','◒','♧','□','♜'].map((m,i)=><button key={i} style={{left:`${16+i*11}%`,top:`${20+(i%3)*23}%`}} onClick={()=>go('spot')}>{m}</button>)}<article><b>川原町通り</b><p>江戸時代の町並みが残る通り。</p><button onClick={()=>go('spot')}>詳しく見る</button></article></section></main>;
 if(view==='post')return <main className="pc-page pc-post"><h1>おすすめやイベントを投稿する</h1><p>あなたの“好き”をシェアしてください</p><section><div><label>関連する場所<input placeholder="例）美濃川沿いの珈琲カフェ"/></label><label>カテゴリー<select><option>選択してください</option><option>FOOD</option></select></label><label>コメント<textarea placeholder="おすすめの理由を記入してください"/></label></div><div className="pc-upload">↥<b>写真を追加（最大5枚）</b><img src={picks[2].image} alt=""/><button className="primary" onClick={()=>{set({post:'投稿を送信しました'});notice('投稿を送信しました。')}}>プレビューを確認する</button></div></section></main>;
 return <Screen view={view} go={go} s={s} set={set} notice={notice}/>;
}
function Screen({view,go,s,set,notice}:{view:View;go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){const p={home:<Home go={go}/>,picks:<Picks go={go} s={s} set={set}/>,event:<Event go={go} s={s} set={set} notice={notice}/>,walk:<Walk go={go} notice={notice}/>,culture:<Culture go={go}/>,experience:<Experience go={go} s={s} set={set} notice={notice}/>,shop:<Shop go={go}/>,drop:<Drop go={go} s={s} set={set} notice={notice}/>,map:<Map go={go}/>,post:<Post go={go} s={s} set={set} notice={notice}/>,mypage:<MyPage go={go} s={s}/>,product:<Product go={go} s={s} set={set} notice={notice}/>,cart:<Cart go={go} s={s} notice={notice}/>,spot:<Spot go={go} s={s} set={set} notice={notice}/>,eventlist:<EventList go={go}/>,search:<Search go={go}/>,favorites:<Favorites go={go} s={s}/>,orders:<Orders go={go} s={s}/>,unlock:<Unlock go={go}/>,custom:<Custom go={go}/>}[view];return <div className={`view view-${view}`}>{p}<Nav view={view} go={go}/></div>}
const board:[string,string,View][]= [['01','ホーム','home'],['02','LOCAL PICKS','picks'],['03','WALK / ROUTE','walk'],['04','EXPERIENCE','experience'],['05','DROP（限定解放）','drop']];
export default function App(){const [view,setView]=useState<View>('home');const [toast,setToast]=useState('');const [s,setS]=useState<AppState>({saved:false,booked:false,unlocked:false,cart:0,name:'岐阜 太郎',color:'紺'});const set=(p:Partial<AppState>)=>setS(x=>({...x,...p}));const notice=(t:string)=>{setToast(t);setTimeout(()=>setToast(''),3400)};const go=(v:View)=>setView(v);return <><main className="desktop-app"><DesktopNav view={view} go={go}/><section className="desktop-screen"><DesktopReference view={view} go={go} s={s} set={set} notice={notice}/></section></main><main className="mobile-app"><Screen view={view} go={go} s={s} set={set} notice={notice}/></main>{toast&&<div className="toast">{toast}</div>}</>}
