'use client';
import { useEffect, useState, type ReactNode } from 'react';

type View='home'|'event'|'walk'|'culture'|'experience'|'experiencedetail'|'shop'|'shoplist'|'maker'|'related'|'checkout'|'complete'|'orderdetail'|'drop'|'map'|'post'|'mypage'|'product'|'cart'|'spot'|'search'|'favorites'|'orders'|'unlock'|'custom'|'eventlist';
type AppState={saved:boolean;booked:boolean;unlocked:boolean;cart:number;post?:string;name:string;color:string};
const picks=[
  {author:'ayako_gifu',title:'柳ケ瀬の路地にある、小さな古書店。',tag:'CULTURE',image:'https://images.unsplash.com/photo-1526243741027-444d633d7365?auto=format&fit=crop&w=800&q=80'},
  {author:'takashi_craft',title:'作家さんのやわらかな器。朝の一杯が少し特別に。',tag:'CRAFT',image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80'},
  {author:'natsuki_foodie',title:'地元の人が通う、午後の喫茶時間。',tag:'FOOD',image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80'}
];
const officialLinks={tourism:'https://www.kankou-gifu.jp/',craft:'https://www.kankou-gifu.jp/article/detail_72.html',prefectureCraft:'https://www.pref.gifu.lg.jp/page/304232.html',prefectureOnline:'https://www.pref.gifu.lg.jp/page/27154.html',gifts:'https://giftsshop.jp/',giftsInfo:'https://www.pref.gifu.lg.jp/page/11931.html',wagasa:'https://wagasa.shop/collections/products',wagasaStory:'https://www.kankou-gifu.jp/article/detail_126.html',casaSpot:'https://www.kankou-gifu.jp/spot/detail_5995.html',minoyaki:'https://www.minoyaki.gr.jp/',minoyakiShop:'https://www.minoyaki.gr.jp/shop',minoyakiCooperative:'https://www.minoyaki.gr.jp/cooperative',minoyakiFacility:'https://www.minoyaki.gr.jp/facility',minoyakiClass:'https://www.minoyaki.gr.jp/facility/class',minoyakiAccess:'https://www.minoyaki.gr.jp/access',kouzan:'https://www.minoyaki.gr.jp/archives/member/mb0054',zohogama:'https://zohogama.com/',hidacolle:'https://www.hida-collection.shop/',hidacolleShop:'https://www.hida-collection.shop/view/page/flagship-shop',ozeki:'https://www.ozeki-lantern.co.jp/index.html',ozekiProducts:'https://www.ozeki-lantern.co.jp/product-aerofoil.html',washi:'https://www.kankou-gifu.jp/spot/detail_1190.html',ukai:'https://www.ukai-gifucity.jp/Ukai/',ukaiMuseum:'https://www.ukaimuseum.jp/',ukaiMuseumGuide:'https://www.ukaimuseum.jp/guide',ukaiMuseumFacility:'https://www.ukaimuseum.jp/facility',ukaiFaq:'https://www.city.gifu.lg.jp/kankoubunka/kankou/1005099/1005111.html',nagaraCruise:'https://www.city.gifu.lg.jp/kankoubunka/kankou/1005099/1025646.html',kawaramachi:'https://www.kankou-gifu.jp/blog/detail_29.html',nagaraExperience:'https://www.gifucvb.or.jp/cmsdesigner/data/entry/digipan/digipan.00025.00000001.pdf',gujo:'https://www.gujohachiman.com/kanko/odori.html'};
function OfficialLink({href,children,className='official-link'}:{href:string;children:ReactNode;className?:string}){return <a className={className} href={href} target="_blank" rel="noreferrer">{children} ↗</a>}
const shopOfficialResources=[
 ['岐阜県公式','伝統的工芸品の一覧',officialLinks.prefectureCraft],
 ['岐阜県公式','県産品をオンラインで購入',officialLinks.prefectureOnline],
 ['岐阜県観光公式','岐阜のすぐれもの・伝統工芸',officialLinks.craft],
 ['美濃焼公式','工芸品のお店・窯元一覧',officialLinks.minoyakiShop],
 ['美濃焼公式','伝統産業会館・展示',officialLinks.minoyakiFacility],
 ['美濃焼公式','陶芸教室・体験案内',officialLinks.minoyakiClass],
 ['岐阜県観光公式','岐阜和傘の文化と作り手',officialLinks.wagasaStory],
 ['店舗公式','THE GIFTS SHOP',officialLinks.gifts]
];
function OfficialDirectory({compact=false}:{compact?:boolean}){return <section className={`official-directory ${compact?'compact':''}`}><header><div><small>OFFICIAL INFORMATION</small><h2>公式情報から、もっと深く知る</h2></div><p>営業時間・在庫・予約条件はリンク先の最新情報をご確認ください。</p></header><div>{shopOfficialResources.map(x=><a key={x[1]} href={x[2]} target="_blank" rel="noreferrer"><small>{x[0]}</small><b>{x[1]}</b><span>公式ページへ　↗</span></a>)}</div></section>}
function PageOfficialLinks({title='関連する公式ページ',items}:{title?:string;items:[string,string][]}){return <section className="page-official-links"><h3>{title}</h3><div>{items.map(x=><OfficialLink key={x[0]} href={x[1]}>{x[0]}</OfficialLink>)}</div></section>}
const products=[['志野焼 湯呑み','¥9,900','https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=500&q=80'],['名入れ和傘','¥33,000','https://images.unsplash.com/photo-1558180700-0c1b2684f8cb?auto=format&fit=crop&w=500&q=80'],['美濃和紙 手漉き便箋','¥2,420','https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=500&q=80']];
function Top({title,back,go}:{title:string;back?:boolean;go:(v:View)=>void}){return <header className="topbar"><button className="icon" onClick={()=>go('home')} aria-label="戻る">{back?'‹':'⌁'}</button><strong>{title}</strong><button className="icon" onClick={()=>go('post')} aria-label="投稿">＋</button></header>}
function Nav({view,go}:{view:View;go:(v:View)=>void}){const n:[View,string,string][]=[['home','⌂','ホーム'],['search','⌕','探す'],['map','◫','マップ'],['shop','♡','ショップ'],['mypage','♙','マイページ']];return <nav className="bottomnav">{n.map(([v,i,l])=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}><span>{i}</span>{l}</button>)}</nav>}
function Row({icon,title,sub,to,go}:{icon:string;title:string;sub:string;to:View;go:(v:View)=>void}){return <button className="menu-row" onClick={()=>go(to)}><span className="menu-icon">{icon}</span><div><b>{title}</b><small>{sub}</small></div><i>›</i></button>}
function Home({go}:{go:(v:View)=>void}){return <MobileTourismHome go={go}/>} 
function Event({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){return <><Top title="EVENT" back go={go}/><main className="content"><div className="event-photo"/><span className="eyebrow">OFFICIAL EVENT</span><h1 className="page-title">郡上おどり</h1><p className="lead">城下町の夜に受け継がれる、岐阜を代表する踊り。</p><hr/><h3>開催情報について</h3><p className="bodycopy">日程、会場、交通規制などは変更される場合があります。お出かけ前に郡上八幡観光協会の公式ページをご確認ください。</p><OfficialLink href={officialLinks.gujo} className="primary">郡上おどり公式情報を見る</OfficialLink><button className="secondary" onClick={()=>{set({booked:true});notice('イベントを保存しました。')}}>{s.booked?'保存済み':'このイベントを保存'}</button></main></>}
const walkSearchUrl='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('岐阜市 柳ケ瀬 文化 工芸 カフェ');
const walkDirectionsUrl='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent('岐阜駅')+'&destination='+encodeURIComponent('川原町通り 岐阜市')+'&waypoints='+encodeURIComponent('柳ケ瀬商店街|岐阜大仏 正法寺');
function LiveWalkMap({compact=false}:{compact?:boolean}){return <section className={`live-walk-map ${compact?'compact':''}`}><iframe title="岐阜市の実地図" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=136.72%2C35.39%2C136.79%2C35.45&layer=mapnik&marker=35.423%2C136.760"/><div><span>岐阜市中心部</span><a href={walkSearchUrl} target="_blank" rel="noreferrer">Google Mapsで周辺を探す ↗</a><a href={walkDirectionsUrl} target="_blank" rel="noreferrer">Google Mapsでルートを開く ↗</a></div></section>}
function Walk({go,notice}:{go:(v:View)=>void;notice:(t:string)=>void}){const stops=['岐阜駅','柳ケ瀬商店街','岐阜大仏 正法寺','川原町通り','長良川うかいミュージアム'];return <><Top title="柳ケ瀬 Arts & Crafts" back go={go}/><main className="content walk"><p className="route-intro">徒歩約 2.6 km　｜　所要時間 約2時間</p><LiveWalkMap compact/><ol>{stops.map((x,i)=><li key={x}><button onClick={()=>go(i===2?'culture':'spot')}><span>{i+1}</span><div><b>{x}</b><small>{i?'徒歩 '+(i+2)+'分':'ルートの出発地点'}</small></div><em>›</em></button></li>)}</ol><a className="primary map-primary" href={walkDirectionsUrl} target="_blank" rel="noreferrer">Google Mapsでこのルートを歩く</a><button className="secondary" onClick={()=>notice('ルートをマイページに保存しました。')}>ルートを保存する</button></main></>}
function Culture({go}:{go:(v:View)=>void}){return <><Top title="CULTURE" back go={go}/><main className="content"><div className="culture-photo"/><span className="eyebrow">GIFU TRADITIONAL CRAFTS</span><h1 className="page-title">岐阜の工芸を、<br/>旅の入口に。</h1><p className="bodycopy">美濃和紙、美濃焼、岐阜和傘、関の刃物、飛騨の木工。土地の自然と技から生まれた工芸をたどります。</p><hr/><h3>岐阜県観光公式情報</h3><p className="bodycopy">工芸の特徴、産地、見学・体験施設について、最新の公式情報を確認できます。</p><OfficialLink href={officialLinks.craft} className="primary">岐阜の伝統工芸品を見る</OfficialLink><button className="secondary" onClick={()=>go('shop')}>公式ショップを探す</button></main></>}
function MobileExperienceList({go}:{go:(v:View)=>void}){
 const [category,setCategory]=useState('すべて');
 const [query,setQuery]=useState('');
 const shown=experienceItems.filter(x=>(category==='すべて'||x.category===category)&&(`${x.title}${x.place}${x.tag}`.includes(query)));
 return <><Top title="GIFU ART & CRAFT" go={go}/><main className="m-exp-index">
  <section className="m-exp-hero" style={{backgroundImage:`linear-gradient(#06182765,#061827d8),url('${homeImages.street}')`}}><span>EXPERIENCE</span><h1>体験する</h1><p>岐阜市で、心に残る特別な時間を。</p></section>
  <section className="m-exp-finder"><div><select aria-label="エリア"><option>エリア</option><option>岐阜市</option><option>美濃市</option></select><select aria-label="日付"><option>日付</option><option>今日</option><option>週末</option></select><select aria-label="人数"><option>人数</option><option>1人</option><option>2人</option></select></div><label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="キーワードで探す"/><span>⌕</span></label></section>
  <div className="m-exp-categories">{experienceCategories.map(x=><button key={x.label} className={category===x.label?'active':''} onClick={()=>setCategory(x.label)}><span>{x.icon}</span><b>{x.label}</b></button>)}</div>
  <section className="m-exp-results"><header><b>{category==='すべて'?'おすすめの体験':category}</b><small>{shown.length}件</small></header>{shown.map(x=><article key={x.title}><button className="m-exp-card-main" onClick={()=>go('experiencedetail')}><img src={x.image} alt=""/><div><em>{x.tag}</em><h2>{x.title}</h2><p>◷ {x.time}　⌖ {x.place}</p><strong>{x.price}</strong><span>★ {x.rating} <small>({x.reviews})</small></span></div></button><OfficialLink href={x.url}>公式情報 ↗</OfficialLink></article>)}</section>
  <button className="m-exp-filter-button" onClick={()=>document.querySelector('.m-exp-finder')?.scrollIntoView({behavior:'smooth'})}>絞り込みを表示</button>
 </main></>
}
function MobileExperienceDetail({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){
 return <><Top title="体験詳細" back go={go}/><main className="m-exp-detail">
  <header><em>自然・川</em><h1>長良川鵜飼観覧</h1><p><b>★ 4.9</b>（256件）</p></header>
  <img className="m-exp-detail-main" src={ukaiImages[4]} alt="長良川鵜飼観覧のイメージ"/>
  <div className="m-exp-thumbs">{ukaiImages.slice(1,5).map((x,i)=><button key={x}><img src={x} alt={`${i+1}枚目`}/></button>)}</div>
  <section className="m-exp-intro"><p>1300年以上受け継がれてきた長良川の鵜飼。川面を照らす篝火と、鵜匠の手縄さばきを観覧船から見届けます。</p><dl><div><dt>◷</dt><dd>約2時間</dd></div><div><dt>♙</dt><dd>1名〜</dd></div><div><dt>文</dt><dd>日本語</dd></div><div><dt>期</dt><dd>5/11–10/15</dd></div></dl></section>
  <section className="m-exp-book"><small>乗船料金・空席</small><h2>公式サイトで確認</h2><OfficialLink href={officialLinks.ukai}>予約・運航カレンダーへ</OfficialLink><button onClick={()=>{set({booked:!s.booked});notice(s.booked?'保存を解除しました。':'体験をお気に入りに保存しました。')}}>{s.booked?'♥ 保存済み':'♡ お気に入りに追加'}</button></section>
  <section className="m-exp-timeline"><h2>体験の流れ（例）</h2>{[['19:00','受付・集合'],['19:15','乗船・出船'],['19:30','鵜飼観覧'],['20:45','下船・解散']].map(x=><div key={x[0]}><time>{x[0]}</time><span/><b>{x[1]}</b></div>)}</section>
  <section className="m-exp-official"><h2>訪れる前に</h2><p>運航日、料金、予約方法は変更される場合があります。必ず公式情報をご確認ください。</p><OfficialLink href={officialLinks.ukaiMuseum}>長良川うかいミュージアム</OfficialLink><OfficialLink href={officialLinks.ukaiFaq}>岐阜市公式・よくある質問</OfficialLink></section>
  <button className="m-exp-back" onClick={()=>go('experience')}>体験一覧へ戻る</button>
 </main></>
}
function Shop({go}:{go:(v:View)=>void}){const makers=[['THE GIFTS SHOP','岐阜県産品'],['和傘CASA','岐阜和傘'],['美濃焼伝統工芸品協同組合','美濃焼'],['株式会社オゼキ','岐阜提灯']];return <><Top title="GIFU ART & CRAFT" go={go}/><main className="content m-shop"><section className="m-shop-cover"><span>SHOP</span><h1>岐阜の手仕事を、<br/>暮らしのそばに。</h1><p>実在する店舗・工房の公式ページへご案内します。</p><button onClick={()=>go('shoplist')}>公式ショップを探す　›</button></section><section className="m-shop-block"><header><h2>岐阜の定番</h2><button onClick={()=>go('shoplist')}>すべて見る</button></header><a className="m-shop-feature" href={officialLinks.gifts} target="_blank" rel="noreferrer"><img src={products[0][2]} alt="THE GIFTS SHOP"/><div><small>岐阜駅・アクティブG</small><b>THE GIFTS SHOP</b><span>公式サイトへ　↗</span></div></a></section><section className="m-shop-block"><header><h2>実在する店・工房</h2><button onClick={()=>go('shoplist')}>すべて見る</button></header><div className="m-maker-row">{makers.map((m,i)=><a key={m[0]} href={[officialLinks.gifts,officialLinks.wagasa,officialLinks.minoyaki,officialLinks.ozeki][i]} target="_blank" rel="noreferrer"><img src={[products[0][2],homeImages.craft,minoyakiMedia.gallery,homeImages.paper][i]} alt=""/><b>{m[0]}</b><small>{m[1]} ↗</small></a>)}</div></section><section className="m-shop-cats">{[['工芸','使う',homeImages.craft],['食','味わう',homeImages.food],['暮らしの道具','見る',homeImages.paper]].map(x=><button key={x[0]} onClick={()=>go('shoplist')} style={{backgroundImage:`linear-gradient(#07182755,#07182799),url('${x[2]}')`}}><b>{x[0]}</b><span>{x[1]}　›</span></button>)}</section><OfficialLink href={officialLinks.giftsInfo} className="m-shop-story"><img src={homeImages.river} alt="清流"/><div><small>岐阜県公式</small><b>県産品販売・情報発信拠点</b><span>公式情報を見る</span></div></OfficialLink><OfficialDirectory compact/></main></>}
function ShopList({go}:{go:(v:View)=>void}){return <><Top title="公式ショップ一覧" back go={go}/><main className="content m-catalog"><div className="m-shop-chips"><b>すべて</b><button>工芸</button><button>陶磁器</button><button>家具・照明</button></div><div className="m-filter-row"><span>公式情報を確認できた6店舗・団体</span></div><section className="m-product-grid">{shopItems.map((x,i)=><a key={x.title} href={x.url} target="_blank" rel="noreferrer"><div><img src={x.image} alt={x.title}/><span>{i===0?'県公式拠点':'公式'}</span><i>↗</i></div><small>{x.tag} / {x.maker}</small><b>{x.title}</b><strong>{x.price}</strong></a>)}</section></main></>}
function Drop({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){return <><Top title="🔒 DROP" back go={go}/><main className="content drop">{!s.unlocked?<section className="unlock"><span>⌘</span><h1>この場所に来た人だけに解放</h1><p>現地QRを読み取って、限定アイテムを解放します。</p><button className="unlock-btn" onClick={()=>{set({unlocked:true});notice('DROPを解放しました。アクセスは3時間有効です。')}}>QRを読み取る</button></section>:<><section className="drop-head"><span className="eyebrow gold">DROP UNLOCKED</span><h1>この場所で解放された<br/>限定アイテム</h1><p>アクセスは3時間有効です。</p></section>{products.map(([n,p,img],i)=><button className="drop-product" key={n} onClick={()=>go('product')}><img src={img} alt={n}/><div><span>{i===0?'現地限定':'限定制作'}</span><b>{n}</b><strong>{p}</strong><small>残り {7-i*2} 点</small></div></button>)}</>}</main></>}
function Map({go}:{go:(v:View)=>void}){const marks=['♜','☕','♜','♨','◒','♜','♧'];return <><Top title="マップで探す" go={go}/><main className="content map"><div className="chipbar"><b>すべて</b><button onClick={()=>go('culture')}>ART</button><button onClick={()=>go('culture')}>CRAFT</button><button onClick={()=>go('spot')}>FOOD</button></div><div className="map-area">{marks.map((m,i)=><button key={i} style={{left:`${10+(i*29)%76}%`,top:`${12+(i*37)%74}%`}} onClick={()=>go(i===1?'spot':'culture')}>{m}</button>)}</div><button className="map-card" onClick={()=>go('spot')}><div><b>喫茶 星時</b><small>カフェ・喫茶　神室町</small><p>レトロな空間で自家焙煎コーヒーを。</p></div><img src={picks[2].image} alt="喫茶店"/></button></main></>}
function Post({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){const [text,setText]=useState('');const [ai,setAi]=useState(false);return <><Top title="おすすめを投稿する" back go={go}/><main className="content form"><div className="upload">＋<small>写真を追加</small></div><label>場所<input defaultValue="喫茶 星時（岐阜市神室町）"/></label><label>ひとことコメント<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="100文字以内で、好きな理由を書いてください。"/></label><label>カテゴリー<select><option>FOOD（カフェ・喫茶）</option><option>CRAFT</option><option>ART</option></select></label><button className="ai-button" onClick={()=>{setAi(true);if(!text)setText('レトロな空間で味わう自家焙煎コーヒー。時間がゆっくり流れます。')}}>✦ AI おすすめサポート</button>{ai&&<div className="ai-result"><b>タイトル案：午後の静かな一杯</b><span>タグ：喫茶 / レトロ / 自家焙煎</span></div>}<button className="primary" onClick={()=>{set({post:text||'午後の静かな一杯'});notice('投稿を送信しました。公開前に確認されます。');go('home')}}>投稿を送信する</button></main></>}
function MyPage({go,s}:{go:(v:View)=>void;s:AppState}){return <><Top title="マイページ" go={go}/><main className="content"><section className="visitor"><span>GIFU VISITOR ID</span><h2>岐阜 太郎</h2><p>GL-2024-000123</p><div><b>訪問スポット<br/><strong>12</strong></b><b>購入アイテム<br/><strong>{s.cart}</strong></b></div></section><h3>あなたのアクション</h3><div className="status-list"><p>♡ 保存　{s.saved?'1件':'0件'}</p><p>✦ 予約　{s.booked?'1件':'0件'}</p><p>🔒 DROP　{s.unlocked?'解放済み':'未解放'}</p></div><button className="primary" onClick={()=>go('post')}>おすすめを投稿する</button></main></>}
function EventList({go}:{go:(v:View)=>void}){return <><Top title="EVENT 一覧" back go={go}/><main className="content"><div className="chipbar"><b>すべて</b><button>ART</button><button>FOOD</button><button>NIGHT</button></div>{['柳ケ瀬アートマーケット','長良川夜市','珈琲と本のある時間'].map((x,i)=><button className="list-card" key={x} onClick={()=>go('event')}><img src={picks[i].image} alt="イベント"/><div><b>{x}</b><small>5/{24+i}　柳ケ瀬　11:00–17:00</small><span>{['ART','NIGHT','FOOD'][i]}</span></div><i>›</i></button>)}</main></>}
function Search({go}:{go:(v:View)=>void}){const [query,setQuery]=useState('');return <><Top title="検索" back go={go}/><main className="content form"><label>キーワード<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="場所・イベント・文化を検索"/></label><div className="chipbar"><b>すべて</b><button onClick={()=>go('spot')}>場所</button><button onClick={()=>go('eventlist')}>イベント</button><button onClick={()=>go('culture')}>文化</button></div>{query&&<button className="list-card" onClick={()=>go('spot')}><img src={picks[2].image} alt="検索結果"/><div><b>{query}に近いおすすめ</b><small>喫茶 星時　岐阜市神室町</small></div><i>›</i></button>}</main></>}
function Favorites({go}:{go:(v:View)=>void;s:AppState}){return <><Top title="お気に入り / 保存一覧" back go={go}/><main className="content m-catalog"><div className="m-shop-chips"><b>すべて</b><button>商品</button><button>体験</button><button>記事</button></div><section className="m-product-grid">{shopItems.slice(0,4).map((x,i)=><button key={x.title} onClick={()=>go(i===0?'product':'related')}><div><img src={x.image} alt=""/><i>♥</i></div><small>{x.tag}</small><b>{x.title}</b><strong>{x.price}</strong></button>)}</section><button className="primary" onClick={()=>go('shoplist')}>保存したい商品を探す</button></main></>}
function Orders({go}:{go:(v:View)=>void;s:AppState}){return <><Top title="注文履歴" back go={go}/><main className="content m-orders"><div className="m-shop-chips"><b>すべて</b><button>発送準備中</button><button>発送済み</button><button>完了</button></div>{shopItems.slice(0,4).map((x,i)=><button key={x.title} className="m-order-row" onClick={()=>go('orderdetail')}><img src={x.image} alt=""/><div><small>GL2024{String(5240001-i).padStart(7,'0')}　2024/05/{24-i}</small><b>{x.title}</b><span>{i===0?'発送準備中':'配送済み'}</span><strong>{x.price}</strong></div></button>)}<button className="secondary" onClick={()=>go('shop')}>ショップへ戻る</button></main></>}
function Custom({go}:{go:(v:View)=>void}){return <><Top title="カスタムオーダー" back go={go}/><main className="content"><img className="product-main" src={products[1][2]} alt="和傘"/><h1 className="page-title">名入れ和傘をつくる</h1><p className="bodycopy">色・柄・名入れを選んで、職人が一点ずつ制作します。</p><button className="primary" onClick={()=>go('product')}>カスタムを始める</button></main></>}
function Unlock({go}:{go:(v:View)=>void}){return <><Top title="DROP 解放" back go={go}/><main className="content drop"><section className="unlock"><span>⌘</span><h1>現地限定DROP</h1><p>QRを読み取ると、3時間だけ限定商品を閲覧できます。</p><button className="unlock-btn" onClick={()=>go('drop')}>解放画面へ進む</button></section></main></>}
function DesktopMenu({go,close}:{go:(v:View)=>void;close:()=>void}){const groups:[string,[View,string,string][]][]=[['4つの楽しみ方',[['eventlist','EVENT','季節の催し'],['walk','WALK','文化を歩いて知る'],['experience','EXPERIENCE','文化に触れる'],['shop','SHOP','作り手の品']]],['便利な機能',[['search','SEARCH','キーワード検索'],['map','MAP','地図から探す'],['post','POST','おすすめを投稿'],['favorites','FAVORITES','保存したもの'],['mypage','MY PAGE','訪問履歴とID']]]];const jump=(v:View)=>{go(v);close()};return <div className="desktop-menu-layer" role="dialog" aria-modal="true" aria-label="サイトメニュー"><button className="desktop-menu-backdrop" onClick={close} aria-label="メニューを閉じる"/><aside className="desktop-menu-panel"><header><div><span>✤</span><div><b>GIFU ART & CRAFT</b><small>サイトメニュー</small></div></div><button onClick={close} aria-label="閉じる">×</button></header><section>{groups.map(([title,items])=><div className="desktop-menu-group" key={title}><h2>{title}</h2>{items.map(([v,en,ja])=><button key={v} onClick={()=>jump(v)}><span>{ja}</span><small>{en}</small><i>›</i></button>)}</div>)}</section><footer><button onClick={()=>jump('home')}>ホームへ</button><button onClick={()=>jump('map')}>地図を開く</button></footer></aside></div>}
function DesktopNav({view,go,onMenu}:{view:View;go:(v:View)=>void;onMenu:()=>void}){const links:[View,string,string][]=[['eventlist','催し','EVENT'],['walk','歩く','WALK'],['experience','体験','EXPERIENCE'],['shop','買う','SHOP']];return <header className="desktop-nav"><button className="desk-brand" onClick={()=>go('home')}>GIFU ART & CRAFT</button><span className="desk-tagline">岐阜のアートに溺れたい</span><button className="desk-search" onClick={()=>go('search')}>場所・体験・イベントを検索　⌕</button><nav>{links.map(([v,ja,en])=><button key={v} className={view===v?'selected':''} onClick={()=>go(v)}><span>{ja}</span><small>{en}</small></button>)}</nav><div className="desk-tools"><button onClick={()=>go('favorites')}>♡<small>お気に入り</small></button><button onClick={()=>go('mypage')}>♙<small>マイページ</small></button><button onClick={onMenu} aria-haspopup="dialog">☰<small>メニュー</small></button></div></header>}
function Product({go}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){return <><Top title="公式ショップ紹介" back go={go}/><main className="content m-product"><div className="m-product-visual"><img src={homeImages.craft} alt="THE GIFTS SHOP"/><span>岐阜駅直結</span></div><small>岐阜県産品販売・情報発信拠点</small><h1>THE GIFTS SHOP</h1><strong>10:00–19:00</strong><div className="m-tabs"><b>店舗について</b><span>アクセス</span><span>取扱品</span></div><article><h2>岐阜のものづくりを、作り手の物語とともに。</h2><p>飛騨の木工、美濃和紙、関の刃物、東濃の陶磁器など、岐阜県各地の県産品を集めた公式拠点です。JR岐阜駅に隣接するアクティブG 2階にあります。</p></article><a className="m-maker-card" href={officialLinks.giftsInfo} target="_blank" rel="noreferrer"><img src={homeImages.maker} alt="岐阜県公式"/><div><small>岐阜県公式ホームページ</small><b>店舗情報・所在地を確認</b><span>岐阜市橋本町1丁目10-1</span></div><i>↗</i></a><div className="m-sticky-actions"><button onClick={()=>go('shoplist')}>ほかの公式店</button><a href={officialLinks.gifts} target="_blank" rel="noreferrer">公式ショップを開く ↗</a></div></main></>}
function Maker({go}:{go:(v:View)=>void}){return <><Top title="産地・団体紹介" back go={go}/><main className="content m-maker"><div className="m-maker-hero"><img src={homeImages.craft} alt="美濃焼"/></div><section className="m-maker-profile"><img src={homeImages.craft} alt=""/><small>美濃焼・土岐市</small><h1>美濃焼伝統工芸品協同組合</h1><p>伝統15品目と、今の暮らしに溶け込む器。</p></section><article><h2>多様な様式を持つ、美濃焼。</h2><p>岐阜県東濃地方で作られる美濃焼の伝統と作り手を紹介する協同組合です。公式サイトでは組合員、窯、展示、陶芸教室、工芸品のオンライン販売を確認できます。</p></article><OfficialLink href={officialLinks.minoyaki} className="secondary">公式サイト・工芸品のお店を見る</OfficialLink><section className="m-related-products"><header><h2>ほかの公式ショップ</h2><button onClick={()=>go('shoplist')}>すべて見る</button></header><div>{shopItems.slice(1,4).map(x=><a key={x.title} href={x.url} target="_blank" rel="noreferrer"><img src={x.image} alt=""/><b>{x.title}</b><small>公式ページ ↗</small></a>)}</div></section><OfficialLink href={officialLinks.washi} className="m-workshop"><div><small>公式体験情報</small><b>美濃和紙の里会館で紙すき体験</b></div><img src={homeImages.paper} alt=""/></OfficialLink></main></>}
function Cart({go,s}:{go:(v:View)=>void;s:AppState;notice:(t:string)=>void}){return <><Top title="カート" back go={go}/><main className="content m-cart"><h2>カート内の商品</h2>{[[products[0][2],'粉引鎬（しのぎ）湯呑','¥3,850'],[shopItems[3].image,'飛騨の漆器 丸盆','¥8,800']].map((x,i)=><div className="m-cart-item" key={x[1]}><img src={x[0]} alt=""/><div><small>{i?'飛騨漆器':'美濃焼'}</small><b>{x[1]}</b><strong>{x[2]}</strong><span>−　1　＋</span></div><button>削除</button></div>)}<section className="m-delivery"><h2>お届け方法</h2><div><span>▣</span><b>通常配送（ヤマト運輸）</b><strong>¥770</strong></div><h2>ギフトオプション</h2><div><span>♧</span><b>ギフト包装を希望する</b><strong>¥330</strong></div></section><div className="m-cart-total"><span>小計 <b>¥12,650</b></span><span>送料 <b>¥770</b></span><span>ギフト包装 <b>¥330</b></span><strong>合計（税込） <b>¥13,750</b></strong></div><button className="primary" onClick={()=>go('checkout')}>購入手続きへ</button></main></>}
function Checkout({go}:{go:(v:View)=>void}){return <><Top title="決済情報入力" back go={go}/><main className="content m-checkout"><section><header><h2>お届け先情報</h2><button>変更</button></header><label>お名前<input defaultValue="山田 太郎"/></label><label>郵便番号<input defaultValue="500-8521"/></label><label>住所<input defaultValue="岐阜県岐阜市橋本町1-10-1"/></label><label>電話番号<input defaultValue="090-1234-5678"/></label></section><section><header><h2>お支払い方法</h2><button>変更</button></header>{['クレジットカード　VISA •••• 1234','コンビニ支払い','PayPay','銀行振込'].map((x,i)=><label className="m-radio" key={x}><input type="radio" name="pay" defaultChecked={i===0}/>{x}</label>)}</section><section className="m-order-summary"><header><h2>ご注文内容</h2><button>変更</button></header><span>商品合計 <b>¥12,650</b></span><span>送料 <b>¥770</b></span><span>ギフト包装 <b>¥330</b></span><strong>合計（税込） <b>¥13,750</b></strong></section><button className="primary" onClick={()=>go('complete')}>注文を確定する</button><small className="m-legal">注文を確定することで、利用規約とプライバシーポリシーに同意したものとみなします。</small></main></>}
function Complete({go}:{go:(v:View)=>void}){return <><Top title="GIFU ART & CRAFT" go={go}/><main className="content m-complete"><div className="m-checkmark">✓</div><h1>ご購入ありがとうございました</h1><p>想いのこもった品物をお届けします。</p><small>注文番号</small><b>GL202405240001</b><section><img src={products[0][2]} alt=""/><div><small>美濃焼</small><b>粉引鎬（しのぎ）湯呑</b><strong>¥6,650</strong></div></section><p>お届け予定<br/><b>6月2日（日）頃</b></p><button className="primary" onClick={()=>go('orders')}>注文履歴を見る</button><button className="secondary" onClick={()=>go('home')}>ホームへ戻る</button></main></>}
function Related({go}:{go:(v:View)=>void}){return <><Top title="文化と体験" back go={go}/><main className="content m-related"><h1>あなたにおすすめの<br/>関連体験・文化</h1><p>購入をきっかけに、ものづくりの背景へ。</p><button className="m-related-feature" onClick={()=>go('experiencedetail')}><img src={homeImages.craft} alt=""/><div><small>美濃焼の産地を巡る</small><b>作り手の想いに触れる旅</b><span>体験を見る　›</span></div></button><h2>関連記事</h2>{[['美濃焼のいまをつくる若き作家たち',homeImages.maker],['釉薬の美しさを生む、土と炎の物語',homeImages.craft]].map(x=><button key={x[0]} className="m-related-row" onClick={()=>go('culture')}><img src={x[1]} alt=""/><b>{x[0]}</b><span>読む　›</span></button>)}<button className="secondary" onClick={()=>go('experience')}>すべての体験・記事を見る</button></main></>}
function OrderDetail({go}:{go:(v:View)=>void}){return <><Top title="注文詳細" back go={go}/><main className="content m-order-detail"><small>注文番号　GL202405240001</small><h1>発送準備中</h1><div className="m-order-track"><b>注文確認</b><b>発送準備中</b><span>発送済み</span><span>配達完了</span></div><p>お届け予定<br/><b>6月2日（日）頃</b></p><section><h2>ご注文商品</h2><div className="m-cart-item"><img src={products[0][2]} alt=""/><div><b>粉引鎬（しのぎ）湯呑</b><small>数量：1点</small><strong>¥6,650</strong></div></div></section><section><h2>お届け先</h2><p>山田 太郎<br/>〒500-8521<br/>岐阜県岐阜市橋本町1-10-1</p></section><button className="secondary" onClick={()=>go('related')}>関連する文化・体験を見る</button></main></>}
function Spot({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){return <><Top title="スポット詳細" back go={go}/><main className="content"><img className="spot-main" src={picks[2].image} alt="喫茶 星時"/><span className="eyebrow">CAFE / KAMUROCHO</span><h1 className="page-title">喫茶 星時</h1><p className="lead">レトロな空間で、自家焙煎コーヒーを。</p><div className="facts"><span>⌖ 神室町</span><span>10:00–18:00</span><span>水曜休</span></div><p className="bodycopy">柳ケ瀬を歩いたあと、ゆっくりと一息つける喫茶店。地元の人がすすめる午後の時間です。</p><button className="primary" onClick={()=>{set({saved:!s.saved});notice(s.saved?'保存を解除しました。':'スポットを保存しました。')}}>{s.saved?'保存を解除する':'♡ 保存する'}</button><button className="secondary" onClick={()=>go('walk')}>この店を含むルートを見る</button></main></>}
const pcCards=[
  ['柳ケ瀬の朝をめぐるモーニング','岐阜市','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80'],
  ['長良川沿いの静かな時間','岐阜市','https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=80'],
  ['金華山のふもと、古かばんの時間','金華山','https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80'],
  ['手仕事の器と閉じる朝','美濃','https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80'],
  ['川原町の風景が好き','川原町','https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=800&q=80']
];
const homeImages={
 street:'https://www.city.gifu.lg.jp/_res/projects/default_project/_page_/001/016/632/kippemippe.jpg',
 mountain:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=82',
 river:'https://images.unsplash.com/photo-1437482078695-73f5ca6c96e2?auto=format&fit=crop&w=900&q=82',
 cafe:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=82',
 craft:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=82',
 festival:'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=82',
 fire:'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=900&q=82',
 forest:'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=82',
 food:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=82',
 paper:'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=900&q=82',
 maker:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=700&q=82',
 woman:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=82',
 spring:'https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=900&q=82',
 autumn:'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=900&q=82',
 winter:'https://images.unsplash.com/photo-1483664852095-d6cc6870702d?auto=format&fit=crop&w=900&q=82'
};
const ukaiImages=[1,2,3,4,5].map(n=>`https://www.ukai-gifucity.jp/Ukai/wp-content/themes/blankslate/slide/${n}.jpg`);
type HomeCard={title:string;sub?:string;image:string;tag?:string;to:View};
function HomeFeatureCard({card,go,tall=false}:{card:HomeCard;go:(v:View)=>void;tall?:boolean}){return <button className={`gl-feature-card ${tall?'tall':''}`} onClick={()=>go(card.to)}><img src={card.image} alt=""/><span className="gl-card-shade"/><div>{card.tag&&<em>{card.tag}</em>}<b>{card.title}</b>{card.sub&&<small>{card.sub}</small>}</div></button>}
function HomeShelf({eyebrow,title,copy,cards,go,variant='standard'}:{eyebrow?:string;title:string;copy:string;cards:HomeCard[];go:(v:View)=>void;variant?:'today'|'events'|'picks'|'walk'|'culture'|'experience'|'people'|'shop'|'seasons'|'standard'}){return <section className={`gl-shelf gl-${variant}`}><header><span>{eyebrow}</span><h2>{title}</h2><p>{copy}</p><button onClick={()=>go(cards[0].to)}>もっと見る　›</button></header><div className="gl-shelf-grid">{cards.map((card,i)=><HomeFeatureCard key={i} card={card} go={go} tall={variant==='today'&&i===0}/>)}</div></section>}
function HomeSlideshow({go}:{go:(v:View)=>void}){const slides=[{tag:'ART',title:'町にひらく、現代美術の窓。',copy:'岐阜の路地とギャラリーを歩く。',image:homeImages.street,to:'walk' as View},{tag:'CRAFT',title:'紙と光がつくる、静かな景色。',copy:'美濃和紙の作り手を訪ねて。',image:homeImages.paper,to:'culture' as View},{tag:'PEOPLE',title:'手の記憶を、次の暮らしへ。',copy:'器をつくる人、その言葉に出会う。',image:homeImages.craft,to:'experience' as View}];const [active,setActive]=useState(0);useEffect(()=>{const timer=setInterval(()=>setActive(v=>(v+1)%slides.length),4800);return()=>clearInterval(timer)},[]);const move=(d:number)=>setActive(v=>(v+d+slides.length)%slides.length);return <section className="gl-slideshow" aria-label="注目のアートと工芸"><div className="gl-slide-viewport"><div className="gl-slide-track" style={{transform:`translateX(-${active*100}%)`}}>{slides.map(slide=><button key={slide.title} className="gl-slide-panel" style={{backgroundImage:`linear-gradient(90deg,#071827de,#07182738),url('${slide.image}')`}} onClick={()=>go(slide.to)}><span>{slide.tag} / FEATURE</span><h2>{slide.title}</h2><p>{slide.copy}</p><em>物語を読む　›</em></button>)}</div><button className="gl-slide-arrow prev" onClick={()=>move(-1)} aria-label="前のスライド">‹</button><button className="gl-slide-arrow next" onClick={()=>move(1)} aria-label="次のスライド">›</button><div className="gl-slide-progress"><i style={{width:`${((active+1)/slides.length)*100}%`}}/></div></div><div className="gl-slide-controls"><b>FEATURED STORIES</b>{slides.map((x,i)=><button key={x.title} className={i===active?'active':''} onClick={()=>setActive(i)} aria-label={`${i+1}枚目を表示`}><span>0{i+1}</span><small>{x.tag}</small></button>)}</div></section>}
function MobileTourismHome({go}:{go:(v:View)=>void}){const mosaic=[{title:'柳ケ瀬、朝のアート散歩',place:'岐阜市',image:homeImages.street,to:'walk' as View},{title:'紙と光のまち、美濃へ',place:'美濃市',image:homeImages.paper,to:'culture' as View},{title:'川辺で出会う、夏の表現',place:'長良川',image:homeImages.river,to:'eventlist' as View}];return <><Top title="GIFU ART & CRAFT" go={go}/><main className="content mobile-tourism-home"><HomeSlideshow go={go}/><section className="mobile-manifesto"><span>MOVING GIFU CITY</span><h1>岐阜のアートに、<br/>溺れたい。</h1><p>見るだけでなく、歩く。触れる。<br/>土地の文化を、自分の感覚で持ち帰る旅へ。</p></section><section className="mobile-editorial"><header><span>LOCAL STORIES</span><h2>いま、出会いたい岐阜。</h2></header><div className="mobile-mosaic">{mosaic.map((x,i)=><button key={x.title} className={i===0?'large':''} onClick={()=>go(x.to)}><img src={x.image} alt=""/><div><small>{x.place}</small><b>{x.title}</b></div></button>)}</div><button className="mobile-text-link" onClick={()=>go('search')}>場所や文化を探す　›</button></section><button className="mobile-wide-story" style={{backgroundImage:`linear-gradient(90deg,#071827e8,#07182742),url('${homeImages.festival}')`}} onClick={()=>go('eventlist')}><small>SEASON / EVENT</small><h2>祭りの熱に、<br/>町の記憶がよみがえる。</h2><span>季節の催しを見る　›</span></button><section className="mobile-experiences"><header><span>EXPERIENCE</span><h2>手で覚える、岐阜の文化。</h2></header><div>{[{title:'和傘づくり',image:'https://images.unsplash.com/photo-1558180700-0c1b2684f8cb?auto=format&fit=crop&w=700&q=82'},{title:'美濃焼ろくろ',image:homeImages.craft},{title:'美濃和紙',image:homeImages.paper}].map(x=><button key={x.title} onClick={()=>go('experience')}><img src={x.image} alt=""/><b>{x.title}</b><small>体験を見る ›</small></button>)}</div></section><button className="mobile-shop-banner" onClick={()=>go('shop')}><div><small>SHOP / PEOPLE</small><h2>作り手の手から、<br/>暮らしの中へ。</h2><span>岐阜の手仕事を見る　›</span></div><img src={homeImages.maker} alt="岐阜の作り手"/></button></main></>}
function PcHome({go}:{go:(v:View)=>void}){
 const today:HomeCard[]=[{tag:'自然',title:'新緑がまぶしい、付知峡で深呼吸を',sub:'中津川市',image:homeImages.mountain,to:'spot'},{tag:'人・暮らし',title:'古い町並みに灯るあかり、高山の夜散歩',sub:'高山市',image:homeImages.street,to:'walk'},{tag:'クラフト',title:'受け継がれる技と美濃焼、土と炎のものづくり',sub:'土岐市',image:homeImages.craft,to:'culture'},{tag:'食',title:'初夏の恵みをいただく、郷土の味',sub:'郡上市',image:homeImages.food,to:'spot'}];
 const events:HomeCard[]=[{tag:'5/24 土',title:'郡上おどり体験イベント',sub:'5/24（土）– 5/31（土）',image:homeImages.festival,to:'event'},{tag:'5/25 日',title:'ぎふ長良川の鵜飼',sub:'5/25（日）– 10/15（水）',image:homeImages.fire,to:'event'},{tag:'5/27 火',title:'飛騨高山 春の登山祭',sub:'5/27（火）– 5/28（水）',image:homeImages.mountain,to:'event'},{tag:'5/31 土',title:'美濃和紙 あかりアート展',sub:'5/31（土）– 6/8（日）',image:homeImages.paper,to:'event'}];
 const local:HomeCard[]=[{tag:'市民のおすすめ',title:'馬籠宿の街並と茶屋',sub:'静かな朝に歩く石畳。',image:homeImages.street,to:'spot'},{tag:'市民のおすすめ',title:'銚子ヶ滝の滝',sub:'マイナスイオンに包まれて。',image:homeImages.forest,to:'spot'},{tag:'市民のおすすめ',title:'古民家カフェ やなぎ',sub:'川の音と珈琲の時間。',image:homeImages.cafe,to:'spot'},{tag:'市民のおすすめ',title:'天空の茶畑',sub:'岐阜の上に広がる景色。',image:homeImages.mountain,to:'spot'}];
 const walk:HomeCard[]=[{title:'高山の古い町並みめぐり',sub:'約2時間　約3.0km',image:homeImages.street,to:'walk'},{title:'美濃のうだつと和紙の里へ',sub:'約2.5時間　約3.5km',image:homeImages.river,to:'walk'},{title:'川原町と長良川めぐり',sub:'約2時間　約2.8km',image:homeImages.mountain,to:'walk'},{title:'馬籠宿から妻籠宿へ中山道ハイク',sub:'約4時間　約6.0km',image:homeImages.forest,to:'walk'}];
 const cultures:HomeCard[]=[{title:'ART',sub:'アート',image:homeImages.street,to:'culture'},{title:'CRAFT',sub:'工芸',image:homeImages.craft,to:'culture'},{title:'FILM',sub:'映画・映像',image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=700&q=82',to:'culture'},{title:'FASHION',sub:'ファッション',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=700&q=82',to:'culture'},{title:'FOOD',sub:'食',image:homeImages.food,to:'culture'},{title:'NIGHT',sub:'ナイトライフ',image:homeImages.street,to:'culture'}];
 const experiences:HomeCard[]=[{tag:'工芸体験',title:'美濃焼ろくろ体験',sub:'¥4,400〜',image:homeImages.craft,to:'experience'},{tag:'自然・アウトドア',title:'長良川カヤック体験',sub:'¥6,500〜',image:homeImages.river,to:'experience'},{tag:'文化体験',title:'和紙づくり体験',sub:'¥3,300〜',image:homeImages.paper,to:'experience'},{tag:'ガイドツアー',title:'まちの案内人と歩く古い町並みツアー',sub:'¥2,000〜',image:homeImages.street,to:'experience'}];
 const people:HomeCard[]=[{title:'辻 徹さん',sub:'美濃焼職人',image:homeImages.maker,to:'culture'},{title:'鈴木 伸一さん',sub:'陶芸家',image:'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=700&q=82',to:'culture'},{title:'加藤 藍さん',sub:'染色作家',image:homeImages.woman,to:'culture'},{title:'山田 真由美さん',sub:'古民家店主',image:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=700&q=82',to:'culture'}];
 const shop:HomeCard[]=[{tag:'県産品総合',title:'THE GIFTS SHOP',sub:'岐阜駅・アクティブG',image:homeImages.craft,to:'product'},{tag:'岐阜和傘',title:'和傘CASA',sub:'岐阜市・川原町',image:'https://images.unsplash.com/photo-1558180700-0c1b2684f8cb?auto=format&fit=crop&w=700&q=82',to:'shoplist'},{tag:'飛騨木工',title:'ヒダコレ',sub:'高山市',image:'https://images.unsplash.com/photo-1528712306091-ed0763094c98?auto=format&fit=crop&w=700&q=82',to:'shoplist'},{tag:'岐阜提灯',title:'株式会社オゼキ',sub:'岐阜市',image:homeImages.paper,to:'shoplist'}];
 const seasons:HomeCard[]=[{title:'春（3–5月）',sub:'桜と花めぐり',image:homeImages.spring,to:'eventlist'},{title:'夏（6–8月）',sub:'清流と夏祭り',image:homeImages.river,to:'eventlist'},{title:'秋（9–11月）',sub:'紅葉と味覚',image:homeImages.autumn,to:'eventlist'},{title:'冬（12–2月）',sub:'雪景色と温泉',image:homeImages.winter,to:'eventlist'}];
 const localPicks=[today[0],{...today[1],tag:undefined},{...local[2],tag:undefined},{...local[3],tag:undefined}];
 const seasonalEvents=[events[0],{...events[1],tag:undefined},{...events[2],tag:undefined},{...seasons[1],tag:undefined}];
 const cultureWalk=[walk[0],walk[1],{...cultures[0],title:'町に残るアートを歩く',sub:'岐阜市',to:'walk' as View},{...cultures[1],title:'手仕事の町・美濃を歩く',sub:'美濃市',to:'walk' as View}];
 const cultureExperience=[experiences[0],{...experiences[1],tag:undefined},{...experiences[2],tag:undefined},{...experiences[3],tag:undefined,title:'文化を知る、和紙づくり体験'}];
 const peopleShop=[shop[0],{...shop[1],tag:undefined},{...shop[2],tag:undefined},{...shop[3],tag:undefined,sub:'森の工房　¥4,950'}];
 return <main className="pc-page gl-home gl-home-simple"><HomeSlideshow go={go}/><section className="gl-manifesto"><span>MOVING GIFU CITY</span><h1>岐阜のアートに溺れたい。</h1><p>土地の人が愛する場所、受け継がれる文化。見るだけでなく、歩き、触れ、自分の感覚で持ち帰る旅へ。</p></section><HomeShelf eyebrow="地元の人が選ぶ場所" title="LOCAL STORIES" copy="今行きたい場所を、土地の人の視点から。" cards={localPicks} go={go} variant="picks"/><HomeShelf eyebrow="季節の催し" title="EVENT" copy="祭り、灯り、今だけの風景。" cards={seasonalEvents} go={go} variant="events"/><HomeShelf eyebrow="文化を歩いて知る" title="WALK" copy="町並みと手仕事をつなぐルート。" cards={cultureWalk} go={go} variant="walk"/><HomeShelf eyebrow="文化に触れる" title="EXPERIENCE" copy="つくり手から学び、手で覚える時間。" cards={cultureExperience} go={go} variant="experience"/><HomeShelf eyebrow="作り手から届く" title="SHOP" copy="人と物語が見える、岐阜の手仕事。" cards={peopleShop} go={go} variant="shop"/><section className="gl-info gl-info-simple"><div><h3>お知らせ</h3><p>2025.05.20　サイトリニューアルのお知らせ</p><p>2025.05.15　夏のイベント特集を公開しました</p></div><div><h3>メールマガジン</h3><p>岐阜の旬な情報を、月に一度お届けします。</p><label><input placeholder="メールアドレスを入力"/><button onClick={()=>alert('登録しました（デモ）')}>登録する ›</button></label></div></section><footer className="gl-footer gl-footer-simple"><div><b>✤ GIFU ART & CRAFT</b><p>岐阜のアートに溺れたい。知る・歩く・体験する・買う。</p></div>{[['EVENT','季節の催し'],['WALK','文化を歩く'],['EXPERIENCE','文化に触れる'],['SHOP','作り手の品']].map(x=><div key={x[0]}><b>{x[0]}</b><small>{x[1]}</small></div>)}<p className="gl-copy">© GIFU ART & CRAFT All Rights Reserved.</p></footer></main>
}
function PcCard({item,go,to='spot'}:{item:string[];go:(v:View)=>void;to?:View}){return <button className="pc-card" onClick={()=>go(to)}><img src={item[2]} alt=""/><b>{item[0]}</b><small>⌖ {item[1]}</small><em>♡ 28　◌ 3</em></button>}
const experienceCategories=[
 {icon:'✦',label:'すべて'},{icon:'⚒',label:'ものづくり'},{icon:'▥',label:'歴史・まち歩き'},{icon:'♨',label:'食・酒'},
 {icon:'◒',label:'自然・川'},{icon:'❖',label:'文化・アート'},{icon:'♙',label:'着物・和傘'},{icon:'☾',label:'夜・プレミアム'}
];
const experienceItems=[
 {category:'着物・和傘',tag:'ものづくり',title:'岐阜和傘づくり体験',copy:'竹の骨と和紙に触れ、受け継がれる手仕事を知る。',place:'岐阜市',time:'約2時間',price:'公式料金',rating:'4.8',reviews:'128',image:'https://images.unsplash.com/photo-1558180700-0c1b2684f8cb?auto=format&fit=crop&w=1200&q=85',url:officialLinks.wagasaStory},
 {category:'ものづくり',tag:'ものづくり',title:'岐阜提灯の絵付け',copy:'美濃和紙と竹ひごが生む、やわらかな灯り。',place:'岐阜市',time:'約90分',price:'公式料金',rating:'4.7',reviews:'96',image:homeImages.paper,url:officialLinks.ozeki},
 {category:'食・酒',tag:'食・酒',title:'美濃焼の器で味わう岐阜の食',copy:'器と郷土の味から、土地の文化をひもとく。',place:'岐阜県内',time:'約90分',price:'公式案内',rating:'4.9',reviews:'74',image:homeImages.food,url:officialLinks.tourism},
 {category:'自然・川',tag:'自然・川',title:'長良川鵜飼観覧',copy:'1300年以上続く伝統を、篝火のそばで体感する夜。',place:'岐阜市・長良川',time:'約2時間',price:'公式料金',rating:'4.9',reviews:'256',image:ukaiImages[4],url:officialLinks.ukai},
 {category:'歴史・まち歩き',tag:'歴史・まち歩き',title:'川原町まち歩きガイド',copy:'格子戸の町並みと長良川の物語を歩いて知る。',place:'岐阜市・川原町',time:'約90分',price:'公式案内',rating:'4.8',reviews:'112',image:homeImages.street,url:officialLinks.kawaramachi},
 {category:'歴史・まち歩き',tag:'歴史・まち歩き',title:'岐阜城と金華山歴史ツアー',copy:'山頂の城から、岐阜の歴史と町を見渡す。',place:'岐阜市・金華山',time:'約3時間',price:'公式案内',rating:'4.8',reviews:'67',image:homeImages.mountain,url:officialLinks.tourism},
 {category:'食・酒',tag:'食・酒',title:'地酒飲み比べ体験',copy:'清流が育てた酒を、土地の話とともに味わう。',place:'岐阜県内',time:'約60分',price:'公式案内',rating:'4.7',reviews:'83',image:homeImages.cafe,url:officialLinks.tourism},
 {category:'着物・和傘',tag:'着物・和傘',title:'着物で川原町散策',copy:'和の装いで、歴史ある町並みをゆっくり歩く。',place:'岐阜市・川原町',time:'約2時間',price:'公式案内',rating:'4.9',reviews:'132',image:homeImages.festival,url:officialLinks.kawaramachi},
 {category:'文化・アート',tag:'文化・アート',title:'美濃和紙の手すき体験',copy:'水と楮から、一枚の白を生み出す。',place:'美濃市',time:'約60分',price:'公式料金',rating:'4.6',reviews:'55',image:homeImages.paper,url:officialLinks.washi},
 {category:'夜・プレミアム',tag:'夜・プレミアム',title:'長良川の夜をめぐる文化散歩',copy:'灯り、川音、町の記憶をたどる夜の時間。',place:'岐阜市',time:'約2時間',price:'公式案内',rating:'4.7',reviews:'68',image:homeImages.street,url:officialLinks.nagaraExperience}
];
const shopItems=[
 {tag:'美濃焼',title:'ミッドナイトブルー ちょこっとカップ',maker:'光山窯',price:'¥2,500（税別）',image:'https://www.minoyaki.gr.jp/minoyaki/wp-content/uploads/2020/10/54-3-1.jpg',url:'https://www.minoyaki.gr.jp/archives/2273'},
 {tag:'美濃焼',title:'粉引兎遊飯碗',maker:'点窯',price:'¥4,000（税別）',image:'https://www.minoyaki.gr.jp/minoyaki/wp-content/uploads/2020/10/70-2-1-1.jpg',url:'https://www.minoyaki.gr.jp/archives/955'},
 {tag:'美濃焼',title:'織部長皿',maker:'あかね陶房',price:'¥5,000（税別）',image:homeImages.craft,url:officialLinks.minoyaki},
 {tag:'美濃焼',title:'鼠志野ぐい呑',maker:'五蓮窯',price:'¥13,000（税別）',image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=85',url:officialLinks.minoyaki},
 {tag:'美濃焼',title:'青織部 ぐい呑',maker:'閑山窯',price:'¥3,000（税別）',image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=85',url:officialLinks.minoyaki},
 {tag:'美濃焼',title:'灰釉葉文淵厚平鉢',maker:'音彩工房',price:'¥5,000（税別）',image:homeImages.paper,url:officialLinks.minoyaki}
];
const minoyakiMedia={
 maker:'https://www.minoyaki.gr.jp/minoyaki/wp-content/uploads/2021/08/IMG_4743-496x500.jpg',
 facility:'https://www.minoyaki.gr.jp/minoyaki/wp-content/uploads/2020/10/kaikan-1.jpg',
 gallery:'https://www.minoyaki.gr.jp/minoyaki/wp-content/uploads/2020/10/k-09.jpg',
 class:'https://www.minoyaki.gr.jp/minoyaki/wp-content/uploads/2020/10/rokuro2.jpg',
 kiln:'https://www.minoyaki.gr.jp/minoyaki/wp-content/uploads/2020/10/kama-1.jpg'
};
const journeySteps:[View,string][]=[['shop','SHOP'],['shoplist','商品一覧'],['product','商品詳細'],['maker','作り手'],['related','文化・体験'],['cart','カート'],['checkout','決済'],['complete','購入完了'],['orderdetail','注文詳細']];
function ShopJourneyNav({view,go}:{view:View;go:(v:View)=>void}){return <nav className="pc-journey-nav" aria-label="ショップ画面一覧">{journeySteps.map(([v,label],i)=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}><span>{i+1}</span>{label}</button>)}</nav>}
function PcExperienceList({go}:{go:(v:View)=>void}){
 const [category,setCategory]=useState('すべて');
 const [query,setQuery]=useState('');
 const shown=experienceItems.filter(x=>(category==='すべて'||x.category===category)&&(`${x.title}${x.place}${x.tag}`.includes(query)));
 return <main className="pc-page exp-index">
  <section className="exp-hero" style={{backgroundImage:`linear-gradient(90deg,#061827bd,#06182745),url('${homeImages.street}')`}}><div><span>EXPERIENCE</span><h1>体験する</h1><p>岐阜市で、心に残る特別な時間を。</p></div><div className="exp-searchbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="キーワードで探す（例：和傘、まち歩き、体験）"/></label><select aria-label="エリアを選択"><option>エリアを選択</option><option>岐阜市</option><option>美濃市</option></select><select aria-label="日付を選択"><option>日付を選択</option><option>今日</option><option>今週末</option></select><select aria-label="人数を選択"><option>人数を選択</option><option>1人</option><option>2人</option><option>3人以上</option></select><button onClick={()=>document.querySelector('.exp-results')?.scrollIntoView({behavior:'smooth'})}>体験する</button></div></section>
  <nav className="exp-categories" aria-label="体験カテゴリー">{experienceCategories.map(x=><button key={x.label} className={category===x.label?'active':''} onClick={()=>setCategory(x.label)}><span>{x.icon}</span><b>{x.label}</b></button>)}</nav>
  <section className="exp-results"><header><div><small>DISCOVER GIFU</small><h2>{category==='すべて'?'岐阜市で見つける、心に残る体験':category}</h2></div><p>{shown.length}件の体験</p></header><div className="exp-grid">{shown.map(x=><article key={x.title}><button className="exp-card-main" onClick={()=>go('experiencedetail')}><div><img src={x.image} alt=""/><em>{x.tag}</em></div><section><h3>{x.title}</h3><p>◷ {x.time}　⌖ {x.place}</p><footer><strong>{x.price}</strong><span>★ {x.rating} <small>({x.reviews})</small></span></footer></section></button><OfficialLink href={x.url}>公式情報 ↗</OfficialLink></article>)}</div></section>
  <section className="exp-season"><div><small>SEASONAL EXPERIENCE</small><h2>岐阜市の体験を、もっと楽しむ。</h2><p>季節の催しやモデルコースから、旅の時間を組み立てる。</p><button onClick={()=>go('eventlist')}>季節ページへ　›</button></div><div>{[homeImages.spring,homeImages.river,homeImages.autumn,homeImages.winter].map((x,i)=><img key={x} src={x} alt={['春','夏','秋','冬'][i]}/>)}</div></section>
 </main>
}
function PcExperienceDetail({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){
 const [photo,setPhoto]=useState(ukaiImages[4]);
 const photos=[ukaiImages[4],ukaiImages[1],ukaiImages[2],ukaiImages[3],ukaiImages[0]];
 return <main className="pc-page exp-detail">
  <div className="exp-breadcrumb"><button onClick={()=>go('experience')}>体験する</button><span>›</span><span>長良川鵜飼観覧</span></div>
  <section className="exp-detail-top"><div className="exp-gallery"><img className="exp-gallery-main" src={photo} alt="長良川鵜飼観覧のイメージ"/><div>{photos.map((x,i)=><button key={x} className={photo===x?'active':''} onClick={()=>setPhoto(x)}><img src={x} alt={`${i+1}枚目を表示`}/></button>)}</div><p>1300年以上受け継がれてきた長良川の鵜飼。篝火が川面を照らす夜、鵜匠の手縄さばきと歴史ある漁法を観覧船から見届けます。</p></div>
   <aside className="exp-booking"><em>自然・川</em><h1>長良川鵜飼観覧</h1><p className="exp-rating">★ 4.9 <span>（256件のレビュー）</span></p><dl><div><dt>場所</dt><dd>岐阜市・長良川</dd></div><div><dt>所要時間</dt><dd>約2時間</dd></div><div><dt>参加人数</dt><dd>1名〜</dd></div><div><dt>言語</dt><dd>日本語</dd></div><div><dt>開催期間</dt><dd>5月11日〜10月15日</dd></div></dl><div className="exp-price"><small>乗船料金・空席</small><strong>公式サイトで確認</strong></div><OfficialLink href={officialLinks.ukai}>予約・運航カレンダーへ</OfficialLink><button className="exp-favorite" onClick={()=>{set({booked:!s.booked});notice(s.booked?'保存を解除しました。':'体験をお気に入りに保存しました。')}}>{s.booked?'♥ 保存済み':'♡ お気に入りに追加'}</button><small>最新の運航状況・料金・予約条件は公式情報を優先してください。</small></aside>
  </section>
  <section className="exp-detail-body"><article><small>EXPERIENCE FLOW</small><h2>体験の流れ（例）</h2><div className="exp-timeline">{[['19:00','受付・集合','乗船場で受付。余裕をもってお越しください。'],['19:15','乗船・出船','長良川へ出船し、川風と夕景を楽しみます。'],['19:30','鵜飼観覧','篝火と鵜匠の技を観覧船から見届けます。'],['20:45','下船・解散','乗船場へ戻り、下船後に解散します。']].map(x=><div key={x[0]}><time>{x[0]}</time><span/><section><h3>{x[1]}</h3><p>{x[2]}</p></section></div>)}</div><p className="exp-note">※時刻や行程は運航日により異なります。公式の運航案内をご確認ください。</p></article><aside><section className="exp-host"><small>HOST</small><h2>ぎふ長良川の鵜飼</h2><p>鵜飼の歴史や見どころを知ってから乗船すると、夜の体験がいっそう深まります。</p><OfficialLink href={officialLinks.ukaiMuseum}>うかいミュージアム公式</OfficialLink></section><section className="exp-meeting"><h2>集合場所を確認</h2><iframe title="長良川うかいミュージアム周辺地図" src="https://www.openstreetmap.org/export/embed.html?bbox=136.755%2C35.433%2C136.782%2C35.452&layer=mapnik&marker=35.442%2C136.771"/><a href="https://www.google.com/maps/search/?api=1&query=長良川うかいミュージアム" target="_blank" rel="noreferrer">Google マップで見る ↗</a></section></aside></section>
  <section className="exp-reviews"><article><small>REVIEWS</small><h2>この体験のレビュー</h2><strong>★ 4.9</strong><p>篝火の熱と川の静けさを同時に感じられる、岐阜ならではの夜でした。</p><span>Yuki　2026.05.12</span></article><div><header><small>NEXT EXPERIENCE</small><h2>あわせておすすめ</h2></header>{experienceItems.slice(4,7).map(x=><button key={x.title} onClick={()=>go('experience')}><img src={x.image} alt=""/><span><b>{x.title}</b><small>{x.place}</small></span></button>)}</div></section>
  <PageOfficialLinks title="長良川鵜飼・周辺体験の公式情報" items={[["ぎふ長良川の鵜飼・予約",officialLinks.ukai],["長良川うかいミュージアム",officialLinks.ukaiMuseum],["施設・観覧案内",officialLinks.ukaiMuseumGuide],["岐阜市公式・鵜飼Q&A",officialLinks.ukaiFaq],["長良川の体験ガイド",officialLinks.nagaraExperience]]}/>
 </main>
}
function PcShopPage({go}:{go:(v:View)=>void}){const officialShops=[['THE GIFTS SHOP','岐阜県産品・岐阜駅',homeImages.craft,officialLinks.gifts],['和傘CASA','岐阜和傘・川原町',shopItems[1].image,officialLinks.wagasa],['美濃焼伝統工芸品協同組合','美濃焼・土岐市',minoyakiMedia.gallery,officialLinks.minoyaki],['ヒダコレ','飛騨木工・高山市',shopItems[4].image,officialLinks.hidacolle]];return <main className="pc-page pc-commerce-home"><section className="pc-commerce-hero"><img src={minoyakiMedia.gallery} alt="美濃焼伝統産業会館の展示"/><div><small>GIFU ART & CRAFT / SHOP</small><h1>岐阜の美しい手仕事と、<br/>文化を暮らしのそばに。</h1><p>実在商品と公式URLを確認し、作り手の物語から選べる入口です。</p><button onClick={()=>go('shoplist')}>商品を見る　›</button></div></section><section className="pc-shop-promises">{[['現地で選ぶ','THE GIFTS SHOP'],['産地を知る','美濃焼と岐阜和傘'],['公式に買う','各オンラインストア']].map((x,i)=><button key={x[0]} onClick={()=>go(i===0?'product':i===1?'maker':'shoplist')}><span>{String(i+1).padStart(2,'0')}</span><b>{x[0]}<br/>{x[1]}</b><i>›</i></button>)}</section><section className="pc-makers"><header><div><small>VERIFIED</small><h2>実在する店舗・工房</h2></div><button onClick={()=>go('shoplist')}>公式商品一覧</button></header><div>{officialShops.map(x=><a key={x[0]} href={x[3]} target="_blank" rel="noreferrer"><img src={x[2]} alt=""/><b>{x[0]}</b><small>{x[1]} ↗</small></a>)}</div></section><section className="pc-shop-editorials"><OfficialLink href={officialLinks.giftsInfo}><img src={products[0][2]} alt=""/><span>岐阜県公式</span><h2>THE GIFTS SHOPの情報</h2></OfficialLink><OfficialLink href={officialLinks.craft}><img src={homeImages.river} alt=""/><span>岐阜県観光公式</span><h2>岐阜の伝統工芸品</h2></OfficialLink><OfficialLink href={officialLinks.washi}><img src={homeImages.paper} alt=""/><span>公式体験情報</span><h2>美濃和紙の里会館</h2></OfficialLink></section><OfficialDirectory/></main>}
function PcShopList({go}:{go:(v:View)=>void}){return <main className="pc-page pc-catalog"><header><small>SHOP / PRODUCTS</small><h1>美濃焼の工芸品 <span>公式掲載商品</span></h1><p>商品を選び、背景を知り、公式販売ページへ。</p></header><aside><b>カテゴリー</b>{['すべての商品','志野','織部','粉引','酒器','うつわ'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}<hr/><b>絞り込み</b>{['現品限り','ギフト向け','食器','酒器'].map(x=><label key={x}><input type="checkbox"/>{x}</label>)}</aside><section><div className="pc-catalog-tools"><div><b>すべて</b><span>新着</span><span>価格順</span><span>窯元別</span></div><small>価格・在庫は公式ページを優先</small></div><div className="pc-catalog-grid">{shopItems.map((x,i)=><article key={x.title}><button onClick={()=>go('product')} aria-label={`${x.title}の詳細を見る`}><div><img src={x.image} alt=""/><span>{i<2?'現品限り':'公式掲載'}</span><i>♡</i></div><small>{x.tag} / {x.maker}</small><h2>{x.title}</h2><b>{x.price}</b></button><OfficialLink href={x.url}>公式商品ページ</OfficialLink></article>)}</div></section></main>}
function PcProductDetail({go,s,set,notice}:{go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){const item=shopItems[0];return <main className="pc-page pc-product-new"><div className="pc-product-gallery"><aside>{[item.image,minoyakiMedia.gallery,minoyakiMedia.kiln,minoyakiMedia.maker].map((x,i)=><img src={x} alt="" key={i}/>)}</aside><img src={item.image} alt={item.title}/></div><section className="pc-product-info"><small>{item.tag} / 土岐市</small><h1>{item.title}</h1><p>{item.maker}　山内 浩子</p><strong>{item.price}</strong><div className="pc-product-rating">現品限り　／　公式商品番号 pr0054_0003</div><p>高さ7.5cm、口径7.5cm。深い青が食卓に静かなアクセントを添える、美濃焼の小さなカップです。</p><label>数量 <select><option>1</option><option>2</option></select></label><label>ギフトラッピング <select><option>希望しない</option><option>希望する（デモ）</option></select></label><button className="pc-gold" onClick={()=>{set({cart:Math.max(1,s.cart)});notice('デモカートに追加しました。');go('cart')}}>デモカートに入れる</button><OfficialLink href={item.url} className="pc-line">公式商品ページで購入</OfficialLink></section><section className="pc-product-story"><article><nav><b>商品について</b><span>素材・仕様</span><span>お手入れ</span><span>窯元について</span></nav><h2>光山窯の、ミッドナイトブルー。</h2><p>商品情報・価格・在庫・発送条件は、美濃焼伝統工芸品協同組合の公式商品ページに接続しています。サイト内のカート以降はUI確認用デモです。</p><button onClick={()=>go('maker')}>作り手・産地を知る　›</button></article><aside><h3>関連する文化・体験</h3><img src={minoyakiMedia.facility} alt="土岐市美濃焼伝統産業会館"/><b>土岐市美濃焼伝統産業会館</b><button onClick={()=>go('related')}>詳しく見る</button><PageOfficialLinks items={[["光山窯・山内浩子さん",officialLinks.kouzan],["美濃焼の公式商品一覧",officialLinks.minoyakiShop],["会館へのアクセス",officialLinks.minoyakiAccess]]}/></aside></section></main>}
function PcMaker({go}:{go:(v:View)=>void}){return <main className="pc-page pc-maker-page"><section className="pc-maker-cover"><div><small>MAKER / KOUZANGAMA</small><h1>光山窯</h1><p>深い青の釉薬で、現代の食卓を彩る。</p><OfficialLink href={officialLinks.kouzan}>公式生産者情報</OfficialLink></div><div className="pc-maker-visual"><img src={minoyakiMedia.kiln} alt="美濃焼の窯"/><img src={shopItems[0].image} alt="光山窯のミッドナイトブルー ちょこっとカップ"/></div></section><section className="pc-maker-bio"><article><small>STORY</small><h2>土と炎に向き合う、<br/>美濃焼の産地。</h2><p>ミッドナイトブルー ちょこっとカップを手がける光山窯。公式商品情報には、生産者・山内浩子さんと土岐市の工房所在地が掲載されています。</p><figure className="pc-maker-profile-card"><img src={minoyakiMedia.maker} alt="光山窯の生産者 山内浩子さん"/><figcaption><b>山内 浩子さん</b><small>光山窯／公式生産者情報の写真</small></figcaption></figure><button onClick={()=>go('related')}>産地の文化・体験を見る　›</button></article><dl><div><dt>窯元</dt><dd>光山窯</dd></div><div><dt>生産者</dt><dd>山内 浩子</dd></div><div><dt>活動地</dt><dd>岐阜県土岐市</dd></div><div><dt>公式情報</dt><dd>美濃焼伝統工芸品協同組合</dd></div></dl></section><section className="pc-maker-products">{shopItems.slice(0,4).map(x=><button key={x.title} onClick={()=>go('product')}><img src={x.image} alt=""/><b>{x.title}</b><small>{x.price}</small></button>)}</section><PageOfficialLinks title="光山窯・美濃焼の公式情報" items={[["光山窯の生産者情報",officialLinks.kouzan],["協同組合・組合員一覧",officialLinks.minoyakiCooperative],["工芸品のお店・窯元一覧",officialLinks.minoyakiShop],["岐阜県の伝統的工芸品",officialLinks.prefectureCraft]]}/></main>}
function PcRelated({go}:{go:(v:View)=>void}){return <main className="pc-page pc-related"><section className="pc-related-lead"><div><small>CULTURE & EXPERIENCE / TOKI</small><h1>器の先にある、<br/>土地と炎の物語。</h1><p>土岐市美濃焼伝統産業会館で、15種類の伝統的な美濃焼と作り手に出会う。</p><OfficialLink href={officialLinks.minoyakiFacility}>会館の公式情報</OfficialLink></div><img src={minoyakiMedia.facility} alt="土岐市美濃焼伝統産業会館"/></section><section className="pc-related-actions"><article><small>EXPERIENCE</small><h2>陶芸教室を確認する</h2><p>開催日・内容・予約方法は公式サイトで最新情報をご確認ください。</p><OfficialLink href={officialLinks.minoyakiClass}>陶芸教室の公式ページへ</OfficialLink></article><article><small>CONTINUE SHOPPING</small><h2>購入ジャーニーを続ける</h2><p>ここから先は決済UIの確認用デモです。実際の購入は公式商品ページで行います。</p><button onClick={()=>go('cart')}>デモカートへ進む　›</button></article></section><PageOfficialLinks title="訪問・体験前に確認する公式情報" items={[["会館の展示・利用案内",officialLinks.minoyakiFacility],["陶芸教室・料金案内",officialLinks.minoyakiClass],["所在地・アクセス",officialLinks.minoyakiAccess],["岐阜県観光公式の伝統工芸特集",officialLinks.craft]]}/><section className="pc-related-grid">{[['美濃焼の展示を訪ねる',minoyakiMedia.gallery],['電動ろくろを体験する',minoyakiMedia.class],['歴史ある窯を知る',minoyakiMedia.kiln]].map((x,i)=><button key={x[0]} onClick={()=>go(i===0?'culture':'product')}><img src={x[1]} alt=""/><h2>{x[0]}</h2><span>詳しく見る　›</span></button>)}</section></main>}
function PcCart({go}:{go:(v:View)=>void}){return <main className="pc-page pc-cart-page"><header><small>UI DEMO / 実購入は公式サイト</small><h1>カート</h1><p>選んだ作品と、お届けの準備。</p></header><section className="pc-cart-items"><h2>カートの中身（2点）</h2>{[[shopItems[0].image,shopItems[0].title,'¥2,750（税込）'],[shopItems[1].image,shopItems[1].title,'¥4,400（税込）']].map(x=><article key={x[1]}><img src={x[0]} alt=""/><div><small>美濃焼伝統工芸品協同組合</small><b>{x[1]}</b><strong>{x[2]}</strong></div><span>−　1　＋</span><button>削除する</button></article>)}<div className="pc-gift"><h3>ギフトオプション</h3><label><input type="checkbox"/>ギフトラッピングを希望する（+¥330）</label><label>メッセージ（任意）<input placeholder="お祝いの言葉"/></label></div></section><aside className="pc-cart-summary"><h2>お届け先・配送方法</h2><p>デモ通常配送<br/>お届け目安：3〜10営業日</p><span>商品合計 <b>¥7,150</b></span><span>送料 <b>¥660</b></span><span>包装 <b>¥330</b></span><strong>合計（税込） <b>¥8,140</b></strong><button onClick={()=>go('checkout')}>購入手続きへ進む</button><PageOfficialLinks title="実際の購入先" items={[[shopItems[0].title,shopItems[0].url],[shopItems[1].title,shopItems[1].url],["美濃焼公式ショップ一覧",officialLinks.minoyakiShop],["岐阜県公式・県産品購入案内",officialLinks.prefectureOnline]]}/></aside></main>}
function PcCheckout({go}:{go:(v:View)=>void}){return <main className="pc-page pc-checkout-page"><header><small>UI DEMO — 入力情報は保存・送信されません</small><h1>決済情報入力</h1><div><b>1 お届け先</b><b>2 お支払い</b><span>3 注文確認</span></div></header><section><div className="pc-form-card"><h2>お届け先</h2><label>お名前<input defaultValue="山田 太郎"/></label><label>郵便番号<input defaultValue="500-8521"/></label><label>住所<input defaultValue="岐阜県岐阜市橋本町1-10-1"/></label><label>電話番号<input defaultValue="090-1234-5678"/></label></div><div className="pc-form-card"><h2>お支払い方法</h2>{['クレジットカード（デモ）','コンビニ支払い（デモ）','銀行振込（デモ）','PayPay（デモ）'].map((x,i)=><label key={x}><input type="radio" name="pcpay" defaultChecked={i===0}/>{x}</label>)}</div></section><aside className="pc-cart-summary"><h2>ご注文内容</h2><span>商品合計 <b>¥7,150</b></span><span>送料 <b>¥660</b></span><span>包装 <b>¥330</b></span><strong>合計（税込） <b>¥8,140</b></strong><button onClick={()=>go('complete')}>デモ注文を確定する</button><small>実際の決済は発生しません。</small></aside></main>}
function PcComplete({go}:{go:(v:View)=>void}){return <main className="pc-page pc-complete-page"><div className="pc-complete-mark">✓</div><small>UI DEMO / THANK YOU</small><h1>注文完了画面を確認しました</h1><p>これは購入体験を確認するためのデモです。実際の注文・決済・発送は発生しません。</p><b>デモ注文番号　GL-DEMO-20260828</b><section>{[['入力内容の確認','ブラウザ外へ送信していません'],['実際の購入について','公式商品ページをご利用ください'],['注文履歴UI','次の画面で確認できます']].map(x=><div key={x[0]}><span>◇</span><b>{x[0]}</b><small>{x[1]}</small></div>)}</section><div className="pc-complete-actions"><button onClick={()=>go('orderdetail')}>注文履歴・詳細を見る</button><button onClick={()=>go('shop')}>SHOPトップへ戻る</button></div><PageOfficialLinks title="実際の商品・購入情報" items={[["美濃焼の公式商品一覧",officialLinks.minoyakiShop],["岐阜県公式・県産品購入案内",officialLinks.prefectureOnline],["THE GIFTS SHOP",officialLinks.gifts]]}/></main>}
function PcOrders({go}:{go:(v:View)=>void}){return <main className="pc-page pc-orders-page"><aside><h2>マイページ</h2><b>注文履歴</b><span>お気に入り</span><span>登録情報</span><span>ログアウト</span></aside><section><header><small>UI DEMO / ORDER HISTORY</small><h1>注文履歴</h1><p>実際の注文記録ではありません。購入後画面の確認用データです。</p></header>{shopItems.slice(0,2).map((x,i)=><button key={x.title} onClick={()=>go('orderdetail')}><img src={x.image} alt=""/><div><small>{i===0?'GL-DEMO-20260828':'GL-DEMO-20260820'}</small><b>{x.title}</b><span>{i===0?'発送準備中（デモ）':'配送済み（デモ）'}</span></div><strong>{i===0?'¥8,140':'¥4,400'}</strong><i>›</i></button>)}</section></main>}
function PcOrderDetail({go}:{go:(v:View)=>void}){return <main className="pc-page pc-order-detail"><aside className="pc-order-menu"><small>MY PAGE</small><h2>マイページ</h2><b>注文履歴</b><button onClick={()=>go('orders')}>履歴一覧</button><button onClick={()=>go('shop')}>SHOPへ戻る</button></aside><section className="pc-order-main"><header><div><small>UI DEMO / ORDER DETAIL</small><h1>注文詳細・購入履歴</h1><p>実際の注文・決済・配送情報ではありません。</p></div><b>注文番号：GL-DEMO-20260828</b></header><section className="pc-order-progress">{['注文受付','入金確認','発送準備中','発送済み','お届け完了'].map((x,i)=><div className={i<3?'done':''} key={x}><span>{i<2?'✓':i===2?'●':'○'}</span><b>{x}</b><small>{i<3?'デモ確認済み':'未処理'}</small></div>)}</section><section className="pc-order-columns"><article><h2>お届け先（デモ）</h2><p>山田 太郎<br/>〒500-8521<br/>岐阜県岐阜市橋本町1-10-1</p><h2>お支払い（デモ）</h2><p>クレジットカード　VISA •••• 1234</p><h2>配送予定</h2><p>3〜10営業日（画面例）</p></article><article><h2>ご注文商品</h2>{shopItems.slice(0,2).map((x,i)=><div key={x.title}><img src={x.image} alt=""/><p><b>{x.title}</b><br/><small>{x.maker}　数量：1点</small></p><strong>{i===0?'¥2,750':'¥4,400'}</strong></div>)}<span>商品合計 <b>¥7,150</b></span><span>送料・包装 <b>¥990</b></span><span>合計（税込） <b>¥8,140</b></span></article></section><div className="pc-order-actions"><OfficialLink href={shopItems[0].url}>1点目の公式商品ページ</OfficialLink><OfficialLink href={shopItems[1].url}>2点目の公式商品ページ</OfficialLink><OfficialLink href={officialLinks.minoyakiShop}>美濃焼の公式商品一覧</OfficialLink><button className="pc-line" onClick={()=>go('related')}>関連する文化・体験を見る</button></div></section></main>}
function PcEventIndex({go}:{go:(v:View)=>void}){const names=['柳ケ瀬アートマーケット','長良川の鵜飼開き','美濃和紙 あかりの夜','郡上おどり はじまりの宵','飛騨の朝市と山の恵み'];return <main className="pc-page editorial-index event-index-pc"><section className="event-season"><div><span>EVENT</span><h1>今だけの景色に、<br/>会いに行く。</h1><p>祭り、川面の灯り、季節の催し。</p></div><button onClick={()=>go('map')}>地図で見る</button></section><div className="event-calendar"><b>5月24日 — 6月8日</b><span>今日</span><span>今週末</span><span>季節</span></div><section className="event-poster-grid">{names.map((n,i)=><button key={n} onClick={()=>go('event')}><div><img src={[homeImages.festival,homeImages.fire,homeImages.paper,homeImages.street,homeImages.food][i]} alt=""/><time><b>{['24','25','31','01','08'][i]}</b><small>{i<3?'MAY':'JUN'}</small></time></div>{i===0&&<span>今週のおすすめ</span>}<h2>{n}</h2><p>{['岐阜市・柳ケ瀬','岐阜市・長良川','美濃市','郡上市','高山市'][i]}</p></button>)}</section></main>}
function PcWalkIndex({go}:{go:(v:View)=>void}){const names=['高山、朝の古い町並み','水の町・郡上八幡を歩く','美濃、うだつと和紙の道','川原町から長良川へ'];return <main className="pc-page editorial-index walk-index-pc"><section className="walk-cover" style={{backgroundImage:`linear-gradient(90deg,#071827ed,#07182728),url('${homeImages.street}')`}}><span>WALK</span><h1>曲がり角の先に、<br/>まだ知らない岐阜。</h1><p>町並みと文化を、歩いて知る。</p><button onClick={()=>go('walk')}>おすすめルートを見る　›</button></section><section className="walk-intro"><div><small>おすすめ</small><h2>柳ケ瀬、手仕事と<br/>喫茶をめぐる午後。</h2><p>職人の工房と喫茶店をつなぐ2.6km。</p><button onClick={()=>go('walk')}>ルート詳細を見る</button></div><LiveWalkMap/></section><section className="route-grid">{names.map((n,i)=><button key={n} onClick={()=>go('walk')}><img src={[homeImages.street,homeImages.river,homeImages.paper,homeImages.mountain][i]} alt=""/><div><h2>{n}</h2><p>◷ 約{2+i%2}時間　　⌖ {2.8+i*.7}km</p></div></button>)}</section></main>}
function DesktopReference({view,go,s,set,notice}:{view:View;go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){
 const cats:[View,string,string][]=[['eventlist','EVENT','イベント'],['walk','WALK / ROUTE','まち歩き'],['culture','CULTURE','文化を知る'],['experience','EXPERIENCE','体験する'],['shop','SHOP','買いもの']];
 const commercePage=view==='shop'?<PcShopPage go={go}/>:view==='shoplist'?<PcShopList go={go}/>:view==='product'?<PcProductDetail go={go} s={s} set={set} notice={notice}/>:view==='maker'?<PcMaker go={go}/>:view==='related'?<PcRelated go={go}/>:view==='cart'?<PcCart go={go}/>:view==='checkout'?<PcCheckout go={go}/>:view==='complete'?<PcComplete go={go}/>:view==='orders'?<PcOrders go={go}/>:view==='orderdetail'?<PcOrderDetail go={go}/>:null;
 if(commercePage)return <div className="pc-commerce-shell"><ShopJourneyNav view={view} go={go}/>{commercePage}</div>;
 if(view==='home')return <PcHome go={go}/>;
 if(view==='eventlist')return <PcEventIndex go={go}/>;
 if(view==='walk')return <PcWalkIndex go={go}/>;
 if(view==='experience')return <PcExperienceList go={go}/>;
 if(view==='experiencedetail')return <PcExperienceDetail go={go} s={s} set={set} notice={notice}/>;
 const titles:Partial<Record<View,[string,string]>>={};
 if(titles[view]){const [title,sub]=titles[view]!;const to=view==='shop'?'product':view==='eventlist'?'event':view==='experience'?'experience':view==='walk'?'walk':'spot';return <main className="pc-page pc-list"><header><div><h1>{title}</h1><p>{sub}</p></div><button className="pc-outline" onClick={()=>go(view==='shop'?'shop':view==='walk'?'map':'post')}>{view==='walk'?'ルートを地図で見る':view==='shop'?'ショップを閲覧する':'投稿する'}</button></header><div className="pc-filters"><b>すべて</b><span>グルメ</span><span>カフェ</span><span>文化</span><span>自然・景観</span><span>買いもの</span><span>子どもと</span></div><section className="pc-card-grid">{pcCards.map((x,i)=><PcCard key={i} item={x} go={go} to={to as View}/>)}</section></main>}
 if(view==='culture')return <main className="pc-page pc-culture"><section className="pc-culture-hero"><div><span>GIFU TRADITIONAL CRAFTS</span><h1>岐阜和傘</h1><b>美しさをひらく、夏のかたち</b><p>細やかな和紙と、竹、手仕事が生む美しさ。公式情報から岐阜の工芸をたどります。</p></div></section><aside><b>主な産地</b><p>岐阜市</p><b>公式情報</b><OfficialLink href={officialLinks.craft}>岐阜県観光公式</OfficialLink></aside><section className="pc-maker"><img src={pcCards[3][2]} alt=""/><div><b>岐阜和傘セレクトショップ 和傘CASA</b><p>実店舗と公式オンラインショップで岐阜和傘を紹介。</p><OfficialLink href={officialLinks.wagasa}>公式ショップを見る</OfficialLink></div></section></main>;
 if(view==='map')return <main className="pc-page pc-map"><aside><input placeholder="スポット・イベントを検索"/><b>すべて</b><span>● おすすめスポット</span><span>● イベント</span><span>● 体験</span><span>● 文化</span><button onClick={()=>go('search')}>リストを表示</button></aside><section className="pc-map-canvas">{['♜','☕','✦','◒','♧','□','♜'].map((m,i)=><button key={i} style={{left:`${16+i*11}%`,top:`${20+(i%3)*23}%`}} onClick={()=>go('spot')}>{m}</button>)}<article><b>川原町通り</b><p>江戸時代の町並みが残る通り。</p><button onClick={()=>go('spot')}>詳しく見る</button></article></section></main>;
 if(view==='post')return <main className="pc-page pc-post"><h1>おすすめやイベントを投稿する</h1><p>あなたの“好き”をシェアしてください</p><section><div><label>関連する場所<input placeholder="例）美濃川沿いの珈琲カフェ"/></label><label>カテゴリー<select><option>選択してください</option><option>FOOD</option></select></label><label>コメント<textarea placeholder="おすすめの理由を記入してください"/></label></div><div className="pc-upload">↥<b>写真を追加（最大5枚）</b><img src={picks[2].image} alt=""/><button className="primary" onClick={()=>{set({post:'投稿を送信しました'});notice('投稿を送信しました。')}}>プレビューを確認する</button></div></section></main>;
 return <Screen view={view} go={go} s={s} set={set} notice={notice}/>;
}
function Screen({view,go,s,set,notice}:{view:View;go:(v:View)=>void;s:AppState;set:(p:Partial<AppState>)=>void;notice:(t:string)=>void}){const p={home:<Home go={go}/>,event:<Event go={go} s={s} set={set} notice={notice}/>,walk:<Walk go={go} notice={notice}/>,culture:<Culture go={go}/>,experience:<MobileExperienceList go={go}/>,experiencedetail:<MobileExperienceDetail go={go} s={s} set={set} notice={notice}/>,shop:<Shop go={go}/>,shoplist:<ShopList go={go}/>,maker:<Maker go={go}/>,related:<Related go={go}/>,checkout:<Checkout go={go}/>,complete:<Complete go={go}/>,orderdetail:<OrderDetail go={go}/>,drop:<Drop go={go} s={s} set={set} notice={notice}/>,map:<Map go={go}/>,post:<Post go={go} s={s} set={set} notice={notice}/>,mypage:<MyPage go={go} s={s}/>,product:<Product go={go} s={s} set={set} notice={notice}/>,cart:<Cart go={go} s={s} notice={notice}/>,spot:<Spot go={go} s={s} set={set} notice={notice}/>,eventlist:<EventList go={go}/>,search:<Search go={go}/>,favorites:<Favorites go={go} s={s}/>,orders:<Orders go={go} s={s}/>,unlock:<Unlock go={go}/>,custom:<Custom go={go}/>}[view];return <div className={`view view-${view}`}>{p}<Nav view={view} go={go}/></div>}
const board:[string,string,View][]= [['01','ホーム','home'],['02','EVENT','eventlist'],['03','WALK / ROUTE','walk'],['04','EXPERIENCE','experience'],['05','DROP（限定解放）','drop']];
export default function App(){const [view,setView]=useState<View>('home');const [menuOpen,setMenuOpen]=useState(false);const [toast,setToast]=useState('');const [s,setS]=useState<AppState>({saved:false,booked:false,unlocked:false,cart:0,name:'岐阜 太郎',color:'紺'});const set=(p:Partial<AppState>)=>setS(x=>({...x,...p}));const notice=(t:string)=>{setToast(t);setTimeout(()=>setToast(''),3400)};const go=(v:View)=>setView(v);return <><main className="desktop-app"><DesktopNav view={view} go={go} onMenu={()=>setMenuOpen(true)}/><section className="desktop-screen"><DesktopReference view={view} go={go} s={s} set={set} notice={notice}/></section>{menuOpen&&<DesktopMenu go={go} close={()=>setMenuOpen(false)}/>}</main><main className="mobile-app"><Screen view={view} go={go} s={s} set={set} notice={notice}/></main>{toast&&<div className="toast">{toast}</div>}</>}
